"""
35-lesson curricula for all 32 pending courses.
Format: (type, title, minutes, xp)
Types: 'reading' | 'exercise' | 'quiz' | 'project'
"""

PENDING_LESSONS = {

  # ════════════════════════════════════════════════════════════════
  # PROGRAMMING
  # ════════════════════════════════════════════════════════════════

  'java': [
    ('reading','Introduction to Java and the JVM Ecosystem',30,75),
    ('reading','Variables, Data Types, and Operators',30,75),
    ('reading','Control Flow: If-Else, Switch, and Ternary',30,75),
    ('reading','Loops: For, While, Do-While, and Enhanced For',30,75),
    ('exercise','Foundation Practice: Calculator and Number Games',50,100),
    ('reading','Classes, Objects, and Constructors',35,75),
    ('reading','Encapsulation and Access Modifiers',35,75),
    ('reading','Inheritance and Method Overriding',35,75),
    ('reading','Polymorphism, Interfaces, and Abstract Classes',35,75),
    ('exercise','OOP Practice: Building a Banking System',50,100),
    ('reading','Arrays and the Java Collections Framework',35,75),
    ('reading','Generics: Type Safety and Wildcards',35,75),
    ('reading','Exception Handling and Custom Exceptions',35,75),
    ('reading','String Manipulation and Regular Expressions',35,75),
    ('exercise','Core APIs Assessment and Practice',50,100),
    ('reading','Lambda Expressions and Functional Interfaces',35,75),
    ('reading','Streams API: Filter, Map, Reduce',35,75),
    ('reading','Optional: Null-Safe Programming',35,75),
    ('reading','Method References and Composing Functions',35,75),
    ('project','Mid-Course Project: E-Commerce Product Catalog',60,150),
    ('reading','Threads, Runnable, and the Executor Framework',35,75),
    ('reading','Synchronization, Locks, and Concurrent Collections',35,75),
    ('reading','CompletableFuture and Async Programming',35,75),
    ('reading','Java 21 Virtual Threads and Structured Concurrency',35,75),
    ('exercise','Concurrency Practice: Multi-threaded Data Processor',50,100),
    ('reading','I/O Streams, NIO.2, and File Handling',35,75),
    ('reading','Java Module System (JPMS)',35,75),
    ('reading','Records, Sealed Classes, and Pattern Matching',35,75),
    ('reading','JVM Internals: Memory Model and Garbage Collection',35,75),
    ('exercise','Modern Java Features Practice',50,100),
    ('reading','Testing with JUnit 5 and Mockito',35,75),
    ('reading','Build Tools: Maven and Gradle',30,75),
    ('reading','Logging, Profiling, and Debugging Java Applications',35,75),
    ('reading','Performance Tuning and JVM Flags',35,75),
    ('project','Capstone: Production-Ready Java Microservice',60,150),
  ],

  'python': [
    ('reading','Introduction to Python: Why Python and How It Works',30,75),
    ('reading','Variables, Data Types, and Basic Operations',30,75),
    ('reading','Strings: Formatting, Methods, and f-Strings',30,75),
    ('reading','Control Flow: If-Else, For, and While Loops',30,75),
    ('exercise','Foundation Practice: Python Scripting Challenges',50,100),
    ('reading','Functions: Definition, Arguments, and Return Values',35,75),
    ('reading','Lists, Tuples, Sets, and Dictionaries',35,75),
    ('reading','List Comprehensions and Generator Expressions',35,75),
    ('reading','File I/O: Reading, Writing, and CSV Handling',35,75),
    ('exercise','Data Structures Practice: Grocery Store Manager',50,100),
    ('reading','Object-Oriented Programming: Classes and Objects',35,75),
    ('reading','Inheritance, Encapsulation, and Polymorphism',35,75),
    ('reading','Modules, Packages, and pip',35,75),
    ('reading','Exception Handling and Debugging Techniques',35,75),
    ('exercise','OOP Assessment: Library Management System',50,100),
    ('reading','Working with Dates, Times, and the datetime Module',30,75),
    ('reading','Regular Expressions with the re Module',35,75),
    ('reading','Decorators and Context Managers',35,75),
    ('reading','Iterators, Generators, and Lazy Evaluation',35,75),
    ('project','Mid-Course Project: Command-Line Task Manager',60,150),
    ('reading','Virtual Environments and Dependency Management',30,75),
    ('reading','Working with JSON, XML, and APIs',35,75),
    ('reading','Web Scraping with BeautifulSoup and Requests',35,75),
    ('reading','Introduction to NumPy and Pandas',35,75),
    ('exercise','Automation Practice: Web Scraper and Data Cleaner',50,100),
    ('reading','Data Visualization with Matplotlib',35,75),
    ('reading','Working with Databases: SQLite and SQLAlchemy',35,75),
    ('reading','Testing with unittest and pytest',35,75),
    ('reading','Concurrency: Threading, Multiprocessing, and asyncio',35,75),
    ('exercise','Advanced Python Practice: Data Pipeline',50,100),
    ('reading','Packaging and Distributing Python Projects',30,75),
    ('reading','Type Hints and Static Analysis with mypy',35,75),
    ('reading','Performance: Profiling and Optimization Techniques',35,75),
    ('reading','Python in Production: Logging, Config, and Deployment',35,75),
    ('project','Capstone: Full-Featured Python Application',60,150),
  ],

  'javascript': [
    ('reading','JavaScript Fundamentals: Variables, Types, and Scope',30,75),
    ('reading','Functions: Declarations, Expressions, and Arrow Functions',30,75),
    ('reading','Objects, Prototypes, and the Prototype Chain',35,75),
    ('reading','Arrays and Array Methods: Map, Filter, Reduce',35,75),
    ('exercise','Foundation Practice: DOM Manipulation Challenges',50,100),
    ('reading','Closures, Currying, and Higher-Order Functions',35,75),
    ('reading','The Event Loop: Call Stack, Web APIs, and Task Queue',35,75),
    ('reading','Promises and the Microtask Queue',35,75),
    ('reading','Async/Await and Error Handling Patterns',35,75),
    ('exercise','Async Practice: Fetch API and Data Dashboard',50,100),
    ('reading','ES Modules: Import, Export, and Module Bundlers',35,75),
    ('reading','Classes and Object-Oriented JavaScript',35,75),
    ('reading','Iterators, Generators, and Symbols',35,75),
    ('reading','WeakMap, WeakSet, and Memory Management',35,75),
    ('exercise','ES2024 Features Assessment and Practice',50,100),
    ('reading','The DOM: Querying, Traversal, and Manipulation',35,75),
    ('reading','Events: Bubbling, Delegation, and Custom Events',35,75),
    ('reading','Web APIs: Fetch, LocalStorage, and IndexedDB',35,75),
    ('reading','Web Workers and SharedArrayBuffer',35,75),
    ('project','Mid-Course Project: Interactive Data Visualization App',60,150),
    ('reading','Functional Programming Patterns in JavaScript',35,75),
    ('reading','Design Patterns: Module, Observer, and Factory',35,75),
    ('reading','Error Handling, Debugging, and Source Maps',35,75),
    ('reading','Testing: Jest, Vitest, and Testing Library',35,75),
    ('exercise','Patterns Practice: Design a Plugin System',50,100),
    ('reading','TypeScript Fundamentals for JavaScript Developers',35,75),
    ('reading','Performance Optimization: Rendering and Memory',35,75),
    ('reading','Security: XSS, CSRF, and Content Security Policy',35,75),
    ('reading','Node.js Basics for JavaScript Developers',35,75),
    ('exercise','Performance and Security Hardening Exercise',50,100),
    ('reading','Tooling: ESLint, Prettier, and Build Pipelines',30,75),
    ('reading','Bundlers: Vite, Webpack, and esbuild',35,75),
    ('reading','JavaScript Runtime Internals: V8 and SpiderMonkey',35,75),
    ('reading','Publishing Packages and Versioning with npm',30,75),
    ('project','Capstone: Full-Featured SPA with Vanilla JS',60,150),
  ],

  'typescript': [
    ('reading','TypeScript Fundamentals: Types, Interfaces, and Enums',30,75),
    ('reading','Type Inference and Type Widening',30,75),
    ('reading','Functions: Typed Parameters, Overloads, and Generics',35,75),
    ('reading','Classes with Access Modifiers and Decorators',35,75),
    ('exercise','Foundation Practice: Type-Safe Utility Library',50,100),
    ('reading','Generics: Constraints, Defaults, and Conditional Types',35,75),
    ('reading','Mapped Types and Template Literal Types',35,75),
    ('reading','Discriminated Unions and Exhaustive Checks',35,75),
    ('reading','Utility Types: Partial, Required, Pick, Omit, Record',35,75),
    ('exercise','Advanced Types Practice: Type-Safe Event System',50,100),
    ('reading','Module System: Declaration Files and DefinitelyTyped',35,75),
    ('reading','Namespaces vs Modules: When to Use Each',30,75),
    ('reading','Declaration Merging and Ambient Declarations',35,75),
    ('reading','The TypeScript Compiler: tsconfig.json Deep Dive',35,75),
    ('exercise','Module and Configuration Practice',50,100),
    ('reading','Type Guards and Narrowing Patterns',35,75),
    ('reading','Infer Keyword and Type Inference in Generics',35,75),
    ('reading','Recursive Types and Deeply Nested Structures',35,75),
    ('reading','Variance: Covariance, Contravariance, and Invariance',35,75),
    ('project','Mid-Course Project: Type-Safe REST API Client',60,150),
    ('reading','TypeScript with React: Props, State, and Hooks Typing',35,75),
    ('reading','TypeScript with Node.js and Express',35,75),
    ('reading','Testing TypeScript: ts-jest and Type-Safe Mocks',35,75),
    ('reading','Performance: Type Instantiation and Compilation Speed',35,75),
    ('exercise','Framework Integration Practice',50,100),
    ('reading','Design Patterns in TypeScript: Repository, CQRS, DI',35,75),
    ('reading','Strict Mode and Gradual Typing Migration',35,75),
    ('reading','Decorators and Metadata Reflection',35,75),
    ('reading','TypeScript 5.x New Features and Roadmap',35,75),
    ('exercise','Production Patterns Practice',50,100),
    ('reading','Monorepo TypeScript Setup with Turborepo',35,75),
    ('reading','Code Generation from Types: Zod and Prisma',35,75),
    ('reading','Linting and Formatting: ESLint with TypeScript',30,75),
    ('reading','Publishing Typed Libraries and Declaration Files',35,75),
    ('project','Capstone: Full-Stack Type-Safe Application',60,150),
  ],

  'go': [
    ('reading','Introduction to Go: Philosophy, Toolchain, and Hello World',30,75),
    ('reading','Variables, Types, and Zero Values',30,75),
    ('reading','Functions, Multiple Returns, and Named Results',30,75),
    ('reading','Control Structures: For, If, Switch, and Defer',30,75),
    ('exercise','Foundation Practice: CLI Tools in Go',50,100),
    ('reading','Structs, Methods, and Embedded Types',35,75),
    ('reading','Interfaces: Implicit Implementation and Composition',35,75),
    ('reading','Pointers: Value vs Reference Semantics',35,75),
    ('reading','Error Handling: Idiomatic Go Error Patterns',35,75),
    ('exercise','OOP Practice: Building a File System Abstraction',50,100),
    ('reading','Slices, Maps, and Arrays in Depth',35,75),
    ('reading','Goroutines and the Go Scheduler',35,75),
    ('reading','Channels: Communication and Synchronization',35,75),
    ('reading','Select Statement and Timeout Patterns',35,75),
    ('exercise','Concurrency Practice: Web Crawler',50,100),
    ('reading','sync Package: Mutex, WaitGroup, and Once',35,75),
    ('reading','Context: Cancellation and Deadlines',35,75),
    ('reading','Go Modules and Dependency Management',30,75),
    ('reading','Testing: go test, Table-Driven Tests, and Benchmarks',35,75),
    ('project','Mid-Course Project: Concurrent REST API Server',60,150),
    ('reading','Standard Library: net/http, encoding/json, os',35,75),
    ('reading','Building REST APIs with net/http and Chi',35,75),
    ('reading','Database Access with database/sql and sqlx',35,75),
    ('reading','Middleware Patterns and Request Lifecycle',35,75),
    ('exercise','API Development Practice: CRUD Service',50,100),
    ('reading','Reflection and the reflect Package',35,75),
    ('reading','Code Generation with go generate',35,75),
    ('reading','Profiling and Optimizing Go Applications',35,75),
    ('reading','Memory Management and Garbage Collection in Go',35,75),
    ('exercise','Performance Optimization Practice',50,100),
    ('reading','Building CLI Tools with cobra',30,75),
    ('reading','gRPC and Protocol Buffers in Go',35,75),
    ('reading','Containerizing Go Applications with Docker',30,75),
    ('reading','Deployment and Observability: Metrics and Tracing',35,75),
    ('project','Capstone: Production Microservice in Go',60,150),
  ],

  'rust': [
    ('reading','Introduction to Rust: Safety, Speed, and Ownership',30,75),
    ('reading','Variables, Data Types, and Mutability',30,75),
    ('reading','Ownership: Move, Copy, and Drop',35,75),
    ('reading','Borrowing and the Borrow Checker',35,75),
    ('exercise','Foundation Practice: Ownership Challenges',50,100),
    ('reading','Lifetimes: Annotating and Elision Rules',35,75),
    ('reading','Structs, Impl Blocks, and Methods',35,75),
    ('reading','Enums, Option, and Result',35,75),
    ('reading','Pattern Matching with match and if let',35,75),
    ('exercise','Type System Practice: Building a Shape Calculator',50,100),
    ('reading','Traits: Defining and Implementing Behaviour',35,75),
    ('reading','Generics: Type Parameters and Trait Bounds',35,75),
    ('reading','Closures and the Fn, FnMut, FnOnce Traits',35,75),
    ('reading','Iterators and the Iterator Trait',35,75),
    ('exercise','Traits and Generics Practice',50,100),
    ('reading','Vectors, Strings, and Hash Maps',35,75),
    ('reading','Error Handling: unwrap, ?, and Custom Error Types',35,75),
    ('reading','Modules, Crates, and Cargo',30,75),
    ('reading','Testing in Rust: Unit, Integration, and Doc Tests',35,75),
    ('project','Mid-Course Project: Command-Line File Utility',60,150),
    ('reading','Smart Pointers: Box, Rc, RefCell, and Arc',35,75),
    ('reading','Concurrency: Threads, Mutex, and Channels',35,75),
    ('reading','Async Rust: Futures, async/await, and Tokio',35,75),
    ('reading','Unsafe Rust: When and How to Use It',35,75),
    ('exercise','Concurrency Practice: Async Web Client',50,100),
    ('reading','Macros: Declarative and Procedural',35,75),
    ('reading','The Foreign Function Interface (FFI)',35,75),
    ('reading','WebAssembly with wasm-bindgen',35,75),
    ('reading','Building Web APIs with Axum',35,75),
    ('exercise','Advanced Rust Features Practice',50,100),
    ('reading','Performance Profiling with perf and flamegraph',35,75),
    ('reading','Memory Layout, Alignment, and SIMD',35,75),
    ('reading','Rust in Embedded Systems',35,75),
    ('reading','Publishing to crates.io and Documentation',30,75),
    ('project','Capstone: High-Performance Systems Tool in Rust',60,150),
  ],

  # ════════════════════════════════════════════════════════════════
  # FRONTEND
  # ════════════════════════════════════════════════════════════════

  'react': [
    ('reading','Introduction to React 19 and the Component Model',30,75),
    ('reading','JSX, Rendering, and the Virtual DOM',30,75),
    ('reading','Props, State, and the Component Lifecycle',35,75),
    ('reading','Event Handling and Synthetic Events',30,75),
    ('exercise','Foundation Practice: Interactive Component Library',50,100),
    ('reading','useState and useReducer: Managing Local State',35,75),
    ('reading','useEffect: Side Effects and Cleanup',35,75),
    ('reading','useRef, useMemo, and useCallback',35,75),
    ('reading','Custom Hooks: Extracting and Reusing Logic',35,75),
    ('exercise','Hooks Practice: Build a Real-Time Dashboard',50,100),
    ('reading','React 19 Actions and the useActionState Hook',35,75),
    ('reading','Server Components and the Client/Server Boundary',35,75),
    ('reading','Suspense, Transitions, and useOptimistic',35,75),
    ('reading','Context API: Global State Without Libraries',35,75),
    ('exercise','React 19 Features Assessment',50,100),
    ('reading','React Router v7: Client-Side Navigation',35,75),
    ('reading','Data Fetching Patterns: SWR and TanStack Query',35,75),
    ('reading','Forms: Controlled, Uncontrolled, and React Hook Form',35,75),
    ('reading','Accessibility in React: ARIA and Focus Management',35,75),
    ('project','Mid-Course Project: Full-Featured Blog Application',60,150),
    ('reading','State Management at Scale with Zustand',35,75),
    ('reading','Performance: Profiling, Memoization, and Code Splitting',35,75),
    ('reading','Testing React: Vitest and React Testing Library',35,75),
    ('reading','Styling: CSS Modules, Tailwind, and CSS-in-JS',35,75),
    ('exercise','Performance and Testing Practice',50,100),
    ('reading','Animation with Framer Motion',35,75),
    ('reading','React and TypeScript: Typing Props, Hooks, and Refs',35,75),
    ('reading','Error Boundaries and Error Handling Patterns',35,75),
    ('reading','Micro-Frontends and Module Federation',35,75),
    ('exercise','Advanced Patterns Practice',50,100),
    ('reading','Deployment: Vercel, Netlify, and Static Export',30,75),
    ('reading','Monitoring: React DevTools and Error Tracking',30,75),
    ('reading','Security: XSS Prevention and Secure Data Handling',35,75),
    ('reading','React Native Overview for React Developers',30,75),
    ('project','Capstone: Production-Grade React Application',60,150),
  ],

  'nextjs': [
    ('reading','Introduction to Next.js and the App Router',30,75),
    ('reading','File-Based Routing: Pages, Layouts, and Templates',30,75),
    ('reading','Server Components vs Client Components',35,75),
    ('reading','Fetching Data in Server Components',35,75),
    ('exercise','Foundation Practice: Multi-Page Marketing Site',50,100),
    ('reading','Static Generation and Dynamic Rendering',35,75),
    ('reading','Caching: Full Route Cache, Data Cache, and Revalidation',35,75),
    ('reading','Incremental Static Regeneration (ISR)',35,75),
    ('reading','Route Handlers and Building API Endpoints',35,75),
    ('exercise','Caching and Rendering Practice',50,100),
    ('reading','Server Actions: Mutations Without API Routes',35,75),
    ('reading','Middleware: Auth, Redirects, and A/B Testing',35,75),
    ('reading','Parallel and Intercepting Routes',35,75),
    ('reading','Loading UI, Suspense, and Streaming',35,75),
    ('exercise','Server Actions Assessment: Form-Driven App',50,100),
    ('reading','Authentication with NextAuth.js v5',35,75),
    ('reading','Database Integration: Prisma and Drizzle ORM',35,75),
    ('reading','Optimistic Updates and useOptimistic',35,75),
    ('reading','Image, Font, and Script Optimisation',35,75),
    ('project','Mid-Course Project: Full-Stack E-Commerce Store',60,150),
    ('reading','Internationalisation (i18n) in Next.js',35,75),
    ('reading','Testing: Playwright, Vitest, and MSW',35,75),
    ('reading','TypeScript Integration and Type-Safe APIs',35,75),
    ('reading','Monitoring and Observability with OpenTelemetry',35,75),
    ('exercise','Testing and Monitoring Practice',50,100),
    ('reading','Deployment to Vercel: Edge Functions and Preview',30,75),
    ('reading','Self-Hosting Next.js on Node.js and Docker',35,75),
    ('reading','Performance: Core Web Vitals and Lighthouse',35,75),
    ('reading','Security: CSP, Rate Limiting, and Input Validation',35,75),
    ('exercise','Deployment and Performance Hardening',50,100),
    ('reading','Micro-Frontends with Next.js and Module Federation',35,75),
    ('reading','Multi-Tenant Architecture in Next.js',35,75),
    ('reading','CMS Integration: Contentful, Sanity, and MDX',35,75),
    ('reading','Monorepo Setup with Turborepo and Next.js',35,75),
    ('project','Capstone: Production SaaS Application',60,150),
  ],

  'angular': [
    ('reading','Introduction to Angular 18 and the CLI',30,75),
    ('reading','Components, Templates, and Data Binding',30,75),
    ('reading','Standalone Components and the New Bootstrap API',35,75),
    ('reading','Directives: Built-In and Custom Attribute Directives',35,75),
    ('exercise','Foundation Practice: Component-Based Dashboard',50,100),
    ('reading','Signals: The New Reactivity Primitive',35,75),
    ('reading','computed() and effect(): Derived State and Side Effects',35,75),
    ('reading','Signal-Based Inputs and Outputs',35,75),
    ('reading','Control Flow: @if, @for, and @switch Syntax',35,75),
    ('exercise','Signals Practice: Reactive Shopping Cart',50,100),
    ('reading','Dependency Injection: Providers and Hierarchical DI',35,75),
    ('reading','Services and the inject() Function',35,75),
    ('reading','HTTP Client: Requests, Interceptors, and Error Handling',35,75),
    ('reading','Angular Router: Lazy Loading and Route Guards',35,75),
    ('exercise','DI and Services Assessment',50,100),
    ('reading','Reactive Forms and Form Validation',35,75),
    ('reading','Angular Animations and Transition API',35,75),
    ('reading','Pipes: Built-In and Custom Pipe Development',35,75),
    ('reading','NgRx Signals Store: State Management',35,75),
    ('project','Mid-Course Project: Enterprise HR Portal',60,150),
    ('reading','RxJS in Angular: Observables, Operators, and Subjects',35,75),
    ('reading','Change Detection: OnPush and Zoneless Angular',35,75),
    ('reading','Testing Angular: Karma, Jest, and Spectator',35,75),
    ('reading','Internationalization (i18n) and Localisation',35,75),
    ('exercise','RxJS and Testing Practice',50,100),
    ('reading','Angular CDK: Overlay, Drag-and-Drop, Virtual Scroll',35,75),
    ('reading','Server-Side Rendering with Angular Universal',35,75),
    ('reading','Progressive Web Apps with Angular',35,75),
    ('reading','Micro-Frontend Architecture with Module Federation',35,75),
    ('exercise','Advanced Angular Patterns Practice',50,100),
    ('reading','Performance: Bundle Optimization and Tree Shaking',35,75),
    ('reading','Security: CSRF Protection and Content Security',35,75),
    ('reading','CI/CD for Angular: GitHub Actions and Firebase Hosting',30,75),
    ('reading','Angular DevTools and Profiling Applications',30,75),
    ('project','Capstone: Enterprise Angular Application',60,150),
  ],

  'vuejs': [
    ('reading','Introduction to Vue 3 and the Composition API',30,75),
    ('reading','Template Syntax, Directives, and Data Binding',30,75),
    ('reading','Reactivity Fundamentals: ref() and reactive()',35,75),
    ('reading','Computed Properties and Watchers',30,75),
    ('exercise','Foundation Practice: Interactive Todo App',50,100),
    ('reading','Components: Props, Emits, and Slots',35,75),
    ('reading','Component Lifecycle Hooks in Composition API',35,75),
    ('reading','Composables: Reusable Logic with Composition API',35,75),
    ('reading','Provide and Inject: Dependency Injection in Vue',35,75),
    ('exercise','Components Practice: Reusable UI Library',50,100),
    ('reading','Vue Router 4: Navigation, Guards, and Lazy Loading',35,75),
    ('reading','Pinia: State Management for Vue 3',35,75),
    ('reading','Forms: v-model, Validation, and VeeValidate',35,75),
    ('reading','Transitions and Animations in Vue',35,75),
    ('exercise','Router and State Management Assessment',50,100),
    ('reading','Async Components and Suspense',35,75),
    ('reading','Custom Directives and Plugins',35,75),
    ('reading','Renderless Components and the Headless Pattern',35,75),
    ('reading','TypeScript with Vue 3: Typed Components and Composables',35,75),
    ('project','Mid-Course Project: Full-Featured E-Commerce SPA',60,150),
    ('reading','Nuxt 3: File-Based Routing and Server-Side Rendering',35,75),
    ('reading','Nuxt 3: Data Fetching with useFetch and useAsyncData',35,75),
    ('reading','Nuxt 3: API Routes and Server Middleware',35,75),
    ('reading','Testing Vue Components with Vitest and Vue Test Utils',35,75),
    ('exercise','Nuxt 3 and Testing Practice',50,100),
    ('reading','Performance: Virtual Scrolling, Lazy Loading, Memoization',35,75),
    ('reading','Accessibility in Vue Applications',30,75),
    ('reading','Internationalization with vue-i18n',30,75),
    ('reading','Micro-Frontends with Vue',35,75),
    ('exercise','Performance and Accessibility Practice',50,100),
    ('reading','Deployment: Netlify, Vercel, and Self-Hosted',30,75),
    ('reading','Vite: Build Tool Deep Dive for Vue Projects',35,75),
    ('reading','Security Best Practices in Vue Applications',35,75),
    ('reading','Vue DevTools and Debugging Techniques',30,75),
    ('project','Capstone: Production Vue 3 / Nuxt 3 Application',60,150),
  ],

  'tailwindcss': [
    ('reading','Introduction to Utility-First CSS and Tailwind Philosophy',30,75),
    ('reading','Core Utilities: Spacing, Sizing, and Layout',30,75),
    ('reading','Typography: Font, Text, and List Utilities',30,75),
    ('reading','Colors, Backgrounds, and Gradients',30,75),
    ('exercise','Foundation Practice: Landing Page with Tailwind',50,100),
    ('reading','Flexbox Utilities: Alignment, Direction, and Wrapping',35,75),
    ('reading','CSS Grid with Tailwind: Columns, Rows, and Placement',35,75),
    ('reading','Responsive Design: Breakpoints and Mobile-First',35,75),
    ('reading','Dark Mode: Class Strategy and Media Strategy',35,75),
    ('exercise','Layout Practice: Responsive Dashboard',50,100),
    ('reading','Hover, Focus, and Other State Variants',35,75),
    ('reading','Transitions, Animations, and Motion',35,75),
    ('reading','Borders, Shadows, Rings, and Outlines',30,75),
    ('reading','Tailwind Configuration: tailwind.config.js Deep Dive',35,75),
    ('exercise','Interactivity and Animation Practice',50,100),
    ('reading','Custom Design Tokens: Extending the Theme',35,75),
    ('reading','Arbitrary Values and CSS Variables',35,75),
    ('reading','@apply Directive and Managing Component Styles',35,75),
    ('reading','Tailwind Plugins: Typography, Forms, and Aspect Ratio',35,75),
    ('project','Mid-Course Project: Design System with Tailwind',60,150),
    ('reading','Component Patterns: Card, Button, Modal, and Navbar',35,75),
    ('reading','Building Accessible Components with Tailwind',35,75),
    ('reading','Tailwind with React: clsx and tailwind-merge',35,75),
    ('reading','Tailwind with Vue and Angular',30,75),
    ('exercise','Component Library Practice',50,100),
    ('reading','Headless UI: Accessible Component Primitives',35,75),
    ('reading','Radix UI and shadcn/ui with Tailwind',35,75),
    ('reading','Optimizing Bundle Size: PurgeCSS and Content Config',35,75),
    ('reading','Tailwind CSS v4: What Changed and Migration Guide',35,75),
    ('exercise','Advanced Tailwind and Framework Integration',50,100),
    ('reading','Building a Custom Component Library for Teams',35,75),
    ('reading','Storybook Integration with Tailwind',30,75),
    ('reading','Design Tokens: Bridging Figma and Tailwind',35,75),
    ('reading','Performance: Critical CSS and Loading Strategies',30,75),
    ('project','Capstone: Full Design System and Component Library',60,150),
  ],

  # ════════════════════════════════════════════════════════════════
  # BACKEND
  # ════════════════════════════════════════════════════════════════

  'nodejs': [
    ('reading','Introduction to Node.js: Event Loop and Non-Blocking I/O',30,75),
    ('reading','Modules: CommonJS, ESM, and the Module System',30,75),
    ('reading','The Core APIs: fs, path, os, and process',35,75),
    ('reading','Streams and Buffers: Efficient Data Processing',35,75),
    ('exercise','Foundation Practice: File Processing CLI Tool',50,100),
    ('reading','HTTP Module: Building a Server from Scratch',35,75),
    ('reading','Express.js: Routing, Middleware, and Request Lifecycle',35,75),
    ('reading','REST API Design: Resources, Verbs, and Status Codes',35,75),
    ('reading','Middleware Patterns: Auth, Logging, and Error Handling',35,75),
    ('exercise','Express Practice: Full CRUD REST API',50,100),
    ('reading','Fastify: High-Performance Alternative to Express',35,75),
    ('reading','Validation with Zod and Input Sanitization',35,75),
    ('reading','Authentication: JWT, Cookies, and Session Management',35,75),
    ('reading','Database Integration: PostgreSQL with node-postgres',35,75),
    ('exercise','Authentication and Database Practice',50,100),
    ('reading','ORM with Prisma: Schema, Migrations, and Queries',35,75),
    ('reading','Caching with Redis: Strategies and TTL',35,75),
    ('reading','WebSockets with ws and Socket.io',35,75),
    ('reading','Job Queues with BullMQ and Redis',35,75),
    ('project','Mid-Course Project: Real-Time Chat API',60,150),
    ('reading','Testing Node.js: Jest, Supertest, and Test Containers',35,75),
    ('reading','Error Handling Patterns and Graceful Shutdown',35,75),
    ('reading','Logging with Winston and Structured Logging',35,75),
    ('reading','Environment Configuration and Secret Management',30,75),
    ('exercise','Testing and Observability Practice',50,100),
    ('reading','Event-Driven Architecture with EventEmitter',35,75),
    ('reading','File Uploads: Multipart, S3, and Streaming',35,75),
    ('reading','Rate Limiting, Throttling, and Security Headers',35,75),
    ('reading','Performance Profiling: node --inspect and Clinic.js',35,75),
    ('exercise','Performance and Security Hardening',50,100),
    ('reading','Clustering and Worker Threads for CPU Tasks',35,75),
    ('reading','Containerizing Node.js with Docker',30,75),
    ('reading','Deployment: PM2, Health Checks, and Zero-Downtime',35,75),
    ('reading','Monitoring with OpenTelemetry and Prometheus',35,75),
    ('project','Capstone: Production-Grade Node.js API Platform',60,150),
  ],

  'spring-boot': [
    ('reading','Introduction to Spring Boot 3 and Spring Framework',30,75),
    ('reading','Spring IoC Container and Dependency Injection',35,75),
    ('reading','Spring MVC: Controllers, RequestMapping, and DTOs',35,75),
    ('reading','Building REST APIs with @RestController',35,75),
    ('exercise','Foundation Practice: CRUD REST API with Spring Boot',50,100),
    ('reading','Spring Data JPA: Entities, Repositories, and JPQL',35,75),
    ('reading','Database Migrations with Flyway and Liquibase',35,75),
    ('reading','Spring Boot Validation with Bean Validation API',35,75),
    ('reading','Exception Handling with @ControllerAdvice',35,75),
    ('exercise','JPA and Data Access Practice',50,100),
    ('reading','Spring Security 6: Authentication and Authorization',35,75),
    ('reading','JWT Authentication and OAuth2 Resource Server',35,75),
    ('reading','Method-Level Security and Custom Access Rules',35,75),
    ('reading','Spring Boot Actuator: Health, Metrics, and Info',35,75),
    ('exercise','Security Assessment: Secured Multi-Role API',50,100),
    ('reading','Spring WebFlux: Reactive Programming with Reactor',35,75),
    ('reading','Spring Cache Abstraction with Redis',35,75),
    ('reading','Spring Events and ApplicationEvent',35,75),
    ('reading','Scheduling Tasks with @Scheduled',30,75),
    ('project','Mid-Course Project: Multi-Tenant SaaS Backend',60,150),
    ('reading','Spring Cloud: Config Server and Service Discovery',35,75),
    ('reading','Spring Cloud Gateway: API Gateway Patterns',35,75),
    ('reading','Resilience4j: Circuit Breaker and Retry',35,75),
    ('reading','Spring Kafka: Event-Driven Microservices',35,75),
    ('exercise','Microservices Practice: Order Processing System',50,100),
    ('reading','Testing Spring Boot: MockMvc, @SpringBootTest, Testcontainers',35,75),
    ('reading','OpenAPI Documentation with springdoc',30,75),
    ('reading','GraalVM Native Image for Spring Boot',35,75),
    ('reading','Performance Tuning: Connection Pools, JPA N+1, Caching',35,75),
    ('exercise','Testing and Performance Practice',50,100),
    ('reading','Containerizing Spring Boot with Docker and Jib',30,75),
    ('reading','Kubernetes Deployment for Spring Boot',35,75),
    ('reading','Observability: Micrometer, Zipkin, and Grafana',35,75),
    ('reading','Spring Authorization Server: Building an OAuth2 Provider',35,75),
    ('project','Capstone: Production Microservices Platform',60,150),
  ],

  'django': [
    ('reading','Introduction to Django: MVT Pattern and Project Structure',30,75),
    ('reading','Models: Fields, Relationships, and Migrations',35,75),
    ('reading','Django ORM: QuerySets, Lookups, and Aggregations',35,75),
    ('reading','Views: Function-Based vs Class-Based Views',35,75),
    ('exercise','Foundation Practice: Blog with Full CRUD',50,100),
    ('reading','URL Configuration and Namespaces',30,75),
    ('reading','Templates: Inheritance, Tags, and Filters',35,75),
    ('reading','Forms: ModelForms, Validation, and Widgets',35,75),
    ('reading','Django Admin: Customisation and Permissions',35,75),
    ('exercise','Forms and Admin Practice: Event Management System',50,100),
    ('reading','Django REST Framework: Serializers and ViewSets',35,75),
    ('reading','DRF Authentication: Token, Session, and JWT',35,75),
    ('reading','DRF Permissions, Throttling, and Filtering',35,75),
    ('reading','API Versioning and Pagination Strategies',35,75),
    ('exercise','DRF Assessment: RESTful E-Commerce API',50,100),
    ('reading','Django Authentication: Login, Registration, and Signals',35,75),
    ('reading','File Uploads: Local Storage and AWS S3',35,75),
    ('reading','Celery: Asynchronous Tasks and Periodic Jobs',35,75),
    ('reading','Django Channels: WebSockets and Real-Time Features',35,75),
    ('project','Mid-Course Project: Real-Time Collaboration Platform',60,150),
    ('reading','Caching with Django and Redis',35,75),
    ('reading','Django Testing: Unit, Integration, and Factory Boy',35,75),
    ('reading','Custom Management Commands and Admin Actions',30,75),
    ('reading','Django Signals and Post-Save Hooks',35,75),
    ('exercise','Async and Caching Practice',50,100),
    ('reading','Database Optimization: Indexes, select_related, prefetch_related',35,75),
    ('reading','Multi-Tenancy Patterns in Django',35,75),
    ('reading','Security: CSRF, SQL Injection, and XSS Prevention',35,75),
    ('reading','Django with Docker: Development and Production Setup',30,75),
    ('exercise','Optimization and Security Practice',50,100),
    ('reading','Deployment: Gunicorn, Nginx, and SSL',35,75),
    ('reading','Static Files and Media in Production with WhiteNoise',30,75),
    ('reading','Monitoring: Sentry, Logging, and Health Checks',35,75),
    ('reading','Scaling Django: Horizontal Scaling and Read Replicas',35,75),
    ('project','Capstone: Production Django SaaS Application',60,150),
  ],

  'fastapi': [
    ('reading','Introduction to FastAPI: Async Python and OpenAPI',30,75),
    ('reading','Path Operations: Routes, Methods, and Status Codes',30,75),
    ('reading','Pydantic v2: Data Validation and Settings Management',35,75),
    ('reading','Request Body, Query Parameters, and Path Parameters',30,75),
    ('exercise','Foundation Practice: Product Catalogue API',50,100),
    ('reading','Dependency Injection with Depends()',35,75),
    ('reading','Authentication: OAuth2 Password Flow and JWT',35,75),
    ('reading','Middleware: CORS, Logging, and Request Timing',35,75),
    ('reading','Background Tasks and the BackgroundTasks Class',30,75),
    ('exercise','Auth and Middleware Practice: User API with Roles',50,100),
    ('reading','SQLAlchemy 2 with FastAPI: Async Sessions',35,75),
    ('reading','Alembic Migrations with FastAPI',30,75),
    ('reading','Repository Pattern and Service Layer',35,75),
    ('reading','File Uploads and Streaming Responses',35,75),
    ('exercise','Database Integration Practice: Task Manager API',50,100),
    ('reading','WebSockets in FastAPI',35,75),
    ('reading','Server-Sent Events and Streaming',35,75),
    ('reading','Celery Integration for Background Jobs',35,75),
    ('reading','Caching with Redis and FastAPI',35,75),
    ('project','Mid-Course Project: Real-Time Notification System',60,150),
    ('reading','Testing FastAPI: pytest, httpx, and TestClient',35,75),
    ('reading','Error Handling and Custom Exception Handlers',35,75),
    ('reading','API Versioning Strategies',30,75),
    ('reading','OpenAPI Customisation: Tags, Descriptions, and Examples',30,75),
    ('exercise','Testing and Documentation Practice',50,100),
    ('reading','Rate Limiting with slowapi',30,75),
    ('reading','Security: Input Sanitisation and OWASP Top 10',35,75),
    ('reading','Containerising FastAPI with Docker',30,75),
    ('reading','Deployment: Uvicorn, Gunicorn, and HTTPS',35,75),
    ('exercise','Security and Deployment Practice',50,100),
    ('reading','Performance: Profiling and Async Optimisation',35,75),
    ('reading','Monitoring with Prometheus and OpenTelemetry',35,75),
    ('reading','GraphQL with Strawberry and FastAPI',35,75),
    ('reading','gRPC with FastAPI and grpcio',35,75),
    ('project','Capstone: Production FastAPI Microservice',60,150),
  ],

  'microservices': [
    ('reading','Introduction to Microservices: Principles and Trade-offs',30,75),
    ('reading','Domain-Driven Design: Bounded Contexts and Aggregates',35,75),
    ('reading','Service Decomposition: Patterns and Anti-Patterns',35,75),
    ('reading','API Gateway Pattern: Routing, Auth, and Rate Limiting',35,75),
    ('exercise','Foundation Practice: Decompose a Monolith',50,100),
    ('reading','Synchronous Communication: REST and gRPC',35,75),
    ('reading','Asynchronous Messaging with Kafka',35,75),
    ('reading','Event-Driven Architecture and Event Sourcing',35,75),
    ('reading','The Saga Pattern: Distributed Transactions',35,75),
    ('exercise','Communication Practice: Order Service with Events',50,100),
    ('reading','CQRS: Separating Commands and Queries',35,75),
    ('reading','Database per Service and Polyglot Persistence',35,75),
    ('reading','Service Discovery: Consul and Kubernetes DNS',35,75),
    ('reading','Load Balancing and Client-Side Load Balancing',35,75),
    ('exercise','CQRS and Data Practice',50,100),
    ('reading','Resilience Patterns: Circuit Breaker, Retry, and Bulkhead',35,75),
    ('reading','Distributed Tracing with Jaeger and OpenTelemetry',35,75),
    ('reading','Centralised Logging with ELK Stack',35,75),
    ('reading','Health Checks and Readiness Probes',30,75),
    ('project','Mid-Course Project: Microservices E-Commerce Platform',60,150),
    ('reading','Service Mesh with Istio: mTLS and Traffic Management',35,75),
    ('reading','API Versioning in Microservices',35,75),
    ('reading','Security: mTLS, Zero-Trust, and Secret Management',35,75),
    ('reading','Testing Microservices: Contract Testing with Pact',35,75),
    ('exercise','Service Mesh and Security Practice',50,100),
    ('reading','Containerisation and Docker Compose for Development',30,75),
    ('reading','Kubernetes for Microservices: Deployments and Services',35,75),
    ('reading','Helm Charts for Microservice Deployment',35,75),
    ('reading','CI/CD Pipelines for Microservices',35,75),
    ('exercise','Deployment and CI/CD Practice',50,100),
    ('reading','Scaling Strategies: Horizontal, Vertical, and Auto-Scaling',35,75),
    ('reading','Cost Optimisation in Microservices Infrastructure',35,75),
    ('reading','Migration from Monolith: Strangler Fig Pattern',35,75),
    ('reading','Governance: Service Ownership and API Standards',30,75),
    ('project','Capstone: Production Microservices Architecture',60,150),
  ],

  # ════════════════════════════════════════════════════════════════
  # CLOUD & DEVOPS
  # ════════════════════════════════════════════════════════════════

  'aws': [
    ('reading','Introduction to AWS: Global Infrastructure and IAM',30,75),
    ('reading','IAM: Users, Roles, Policies, and Best Practices',35,75),
    ('reading','EC2: Instances, AMIs, and Auto Scaling Groups',35,75),
    ('reading','VPC: Subnets, Route Tables, and Security Groups',35,75),
    ('exercise','Foundation Practice: Secure Multi-Tier VPC',50,100),
    ('reading','S3: Buckets, Policies, Versioning, and Lifecycle',35,75),
    ('reading','RDS and Aurora: Managed Relational Databases',35,75),
    ('reading','ElastiCache: Redis and Memcached on AWS',35,75),
    ('reading','DynamoDB: NoSQL at Scale with Single-Table Design',35,75),
    ('exercise','Storage and Database Practice: Data Lake Setup',50,100),
    ('reading','Lambda: Serverless Functions and Triggers',35,75),
    ('reading','API Gateway: REST and HTTP APIs',35,75),
    ('reading','SQS and SNS: Messaging and Pub/Sub',35,75),
    ('reading','EventBridge: Event-Driven Architectures on AWS',35,75),
    ('exercise','Serverless Practice: Event-Driven Order Processor',50,100),
    ('reading','ECS and Fargate: Containerised Workloads',35,75),
    ('reading','EKS: Managed Kubernetes on AWS',35,75),
    ('reading','CloudFront: CDN, Edge Functions, and Caching',35,75),
    ('reading','Route 53: DNS, Health Checks, and Failover',35,75),
    ('project','Mid-Course Project: Serverless SaaS Architecture',60,150),
    ('reading','CloudFormation: Infrastructure as Code',35,75),
    ('reading','AWS CDK: Cloud Infrastructure with TypeScript',35,75),
    ('reading','CloudWatch: Logs, Metrics, and Alarms',35,75),
    ('reading','X-Ray: Distributed Tracing on AWS',35,75),
    ('exercise','IaC and Observability Practice',50,100),
    ('reading','Secrets Manager and Parameter Store',30,75),
    ('reading','AWS WAF, Shield, and Security Hub',35,75),
    ('reading','Cost Optimisation: Reserved Instances and Savings Plans',35,75),
    ('reading','Multi-Region Architecture and Disaster Recovery',35,75),
    ('exercise','Security and Cost Optimisation Practice',50,100),
    ('reading','AWS Well-Architected Framework: Five Pillars',35,75),
    ('reading','Step Functions: Orchestrating Serverless Workflows',35,75),
    ('reading','Glue and Athena: Serverless Data Analytics',35,75),
    ('reading','Exam Preparation: Solutions Architect Associate',35,75),
    ('project','Capstone: Resilient Multi-Region AWS Architecture',60,150),
  ],

  'docker': [
    ('reading','Introduction to Containers and Docker Architecture',30,75),
    ('reading','Installing Docker and Running Your First Container',20,50),
    ('reading','Docker Images: Layers, Registries, and Pulling',30,75),
    ('reading','Writing Dockerfiles: Instructions and Best Practices',35,75),
    ('exercise','Foundation Practice: Containerise a Web Application',50,100),
    ('reading','Multi-Stage Builds for Smaller Production Images',35,75),
    ('reading','Docker Volumes: Persistent Data and Bind Mounts',35,75),
    ('reading','Docker Networking: Bridge, Host, and Overlay',35,75),
    ('reading','Environment Variables and Docker Secrets',30,75),
    ('exercise','Intermediate Practice: Multi-Container Application',50,100),
    ('reading','Docker Compose: Defining Multi-Service Applications',35,75),
    ('reading','Docker Compose: Networks, Volumes, and Profiles',35,75),
    ('reading','Health Checks and Dependency Management',30,75),
    ('reading','Docker Compose for Development Environments',35,75),
    ('exercise','Docker Compose Practice: Full-Stack Dev Environment',50,100),
    ('reading','Container Security: Rootless Docker and Image Scanning',35,75),
    ('reading','Docker Content Trust and Image Signing',35,75),
    ('reading','Resource Limits: CPU, Memory, and cgroups',35,75),
    ('reading','Logging Drivers and Centralised Log Aggregation',35,75),
    ('project','Mid-Course Project: Production-Ready Container Stack',60,150),
    ('reading','Docker Registry: Hosting a Private Registry',35,75),
    ('reading','Pushing to Docker Hub, ECR, and GCR',30,75),
    ('reading','CI/CD Pipelines with Docker: GitHub Actions',35,75),
    ('reading','BuildKit and Advanced Build Features',35,75),
    ('exercise','Registry and CI/CD Practice',50,100),
    ('reading','Docker Swarm: Orchestration Basics',35,75),
    ('reading','Transitioning from Docker Swarm to Kubernetes',35,75),
    ('reading','Debugging Containers: exec, logs, and inspect',30,75),
    ('reading','Performance: Image Size Optimisation and Layer Caching',35,75),
    ('exercise','Orchestration and Debugging Practice',50,100),
    ('reading','Podman and OCI Alternatives to Docker',30,75),
    ('reading','Dev Containers: VS Code and Codespaces',30,75),
    ('reading','Monitoring Containers: cAdvisor and Prometheus',35,75),
    ('reading','Docker in Production: Rollouts and Rollbacks',35,75),
    ('project','Capstone: Container-Native Microservices Platform',60,150),
  ],

  'kubernetes': [
    ('reading','Introduction to Kubernetes: Architecture and Components',30,75),
    ('reading','Pods: The Smallest Deployable Unit',35,75),
    ('reading','Deployments: Replicas, Rolling Updates, and Rollbacks',35,75),
    ('reading','Services: ClusterIP, NodePort, and LoadBalancer',35,75),
    ('exercise','Foundation Practice: Deploy a Multi-Tier Application',50,100),
    ('reading','ConfigMaps and Secrets: Configuration Management',35,75),
    ('reading','Namespaces and Resource Quotas',35,75),
    ('reading','Ingress Controllers and TLS Termination',35,75),
    ('reading','Persistent Volumes and Storage Classes',35,75),
    ('exercise','Config and Storage Practice',50,100),
    ('reading','StatefulSets for Stateful Applications',35,75),
    ('reading','DaemonSets and Jobs: Cluster-Wide and Batch Workloads',35,75),
    ('reading','Horizontal Pod Autoscaler and Cluster Autoscaler',35,75),
    ('reading','Resource Requests and Limits: QoS Classes',35,75),
    ('exercise','Workloads Assessment: Stateful Database Cluster',50,100),
    ('reading','RBAC: Roles, ClusterRoles, and Bindings',35,75),
    ('reading','ServiceAccounts and Pod Security Standards',35,75),
    ('reading','NetworkPolicies: Segmenting Pod Traffic',35,75),
    ('reading','Secrets Management with External Secrets Operator',35,75),
    ('project','Mid-Course Project: Production Multi-Tier Application',60,150),
    ('reading','Helm: Packaging and Deploying Kubernetes Applications',35,75),
    ('reading','Helm Charts: Writing, Testing, and Publishing',35,75),
    ('reading','Operators: Custom Resources and Controllers',35,75),
    ('reading','GitOps with Argo CD: Declarative Deployments',35,75),
    ('exercise','Helm and GitOps Practice',50,100),
    ('reading','Istio Service Mesh: Traffic Management and mTLS',35,75),
    ('reading','Observability: Prometheus, Grafana, and Loki',35,75),
    ('reading','Distributed Tracing with Jaeger in Kubernetes',35,75),
    ('reading','Cluster Upgrades and Node Maintenance',35,75),
    ('exercise','Service Mesh and Observability Practice',50,100),
    ('reading','Multi-Cluster Kubernetes: Federation and Argo CD',35,75),
    ('reading','Cost Optimisation: Spot Instances and Resource Right-Sizing',35,75),
    ('reading','Disaster Recovery and Backup with Velero',35,75),
    ('reading','CKA Exam Preparation and Tips',35,75),
    ('project','Capstone: Enterprise Kubernetes Platform',60,150),
  ],

  'terraform': [
    ('reading','Introduction to IaC and Terraform Architecture',30,75),
    ('reading','HCL Syntax: Resources, Variables, and Outputs',30,75),
    ('reading','Providers: AWS, GCP, Azure, and Kubernetes',35,75),
    ('reading','Terraform Workflow: init, plan, apply, destroy',30,75),
    ('exercise','Foundation Practice: AWS VPC with Terraform',50,100),
    ('reading','Variables: Types, Validation, and Sensitive Values',35,75),
    ('reading','Locals, Data Sources, and Dynamic Blocks',35,75),
    ('reading','State: Local, Remote, and State Locking',35,75),
    ('reading','Workspaces: Environment Separation',30,75),
    ('exercise','State and Variables Practice: Multi-Environment Setup',50,100),
    ('reading','Modules: Writing, Using, and Publishing',35,75),
    ('reading','Module Composition and Dependency Management',35,75),
    ('reading','Terraform Registry and Community Modules',30,75),
    ('reading','Count, For Each, and Dynamic Resource Creation',35,75),
    ('exercise','Modules Practice: Reusable AWS Infrastructure Library',50,100),
    ('reading','Provisioners: Local-Exec and Remote-Exec',35,75),
    ('reading','Null Resources and Triggers',30,75),
    ('reading','Managing Kubernetes with the Kubernetes Provider',35,75),
    ('reading','Helm Provider: Deploying Charts with Terraform',35,75),
    ('project','Mid-Course Project: Full AWS Infrastructure Stack',60,150),
    ('reading','Remote State with S3, DynamoDB, and Terraform Cloud',35,75),
    ('reading','Terragrunt: DRY Terraform at Scale',35,75),
    ('reading','Atlantis: Automated Terraform Pull Requests',35,75),
    ('reading','CI/CD for Terraform: GitHub Actions and Pipelines',35,75),
    ('exercise','Remote State and CI/CD Practice',50,100),
    ('reading','Policy as Code: Sentinel and Open Policy Agent',35,75),
    ('reading','Drift Detection and Reconciliation',35,75),
    ('reading','Testing Terraform: Terratest and tftest',35,75),
    ('reading','Security: Secrets in Terraform and Vault Integration',35,75),
    ('exercise','Policy, Testing, and Security Practice',50,100),
    ('reading','Refactoring Terraform: Moved Blocks and State Surgery',35,75),
    ('reading','Multi-Cloud Deployments with Terraform',35,75),
    ('reading','Cost Estimation with Infracost',30,75),
    ('reading','Terraform CDK: IaC with TypeScript and Python',35,75),
    ('project','Capstone: Multi-Cloud Infrastructure Platform',60,150),
  ],

  # ════════════════════════════════════════════════════════════════
  # AI/ML (stub versions)
  # ════════════════════════════════════════════════════════════════

  'ml-fundamentals': [
    ('reading','Introduction to Machine Learning: Types and Applications',30,75),
    ('reading','Python for ML: NumPy, Pandas, and Matplotlib Recap',30,75),
    ('reading','Data Preprocessing: Cleaning, Encoding, and Scaling',35,75),
    ('reading','Feature Engineering: Selection and Transformation',35,75),
    ('exercise','Foundation Practice: EDA and Preprocessing Pipeline',50,100),
    ('reading','Linear Regression: Theory and Implementation',35,75),
    ('reading','Polynomial Regression and Regularisation',35,75),
    ('reading','Logistic Regression for Classification',35,75),
    ('reading','Model Evaluation: Accuracy, Precision, Recall, F1',35,75),
    ('exercise','Regression and Classification Practice',50,100),
    ('reading','Decision Trees and Random Forests',35,75),
    ('reading','Gradient Boosting: XGBoost, LightGBM, CatBoost',35,75),
    ('reading','Support Vector Machines',35,75),
    ('reading','k-Nearest Neighbours and Naive Bayes',35,75),
    ('exercise','Ensemble Methods Assessment',50,100),
    ('reading','Cross-Validation and Hyperparameter Tuning',35,75),
    ('reading','Overfitting, Underfitting, and the Bias-Variance Trade-off',35,75),
    ('reading','Pipelines with scikit-learn',35,75),
    ('reading','Unsupervised Learning: K-Means and DBSCAN',35,75),
    ('project','Mid-Course Project: End-to-End Classification System',60,150),
    ('reading','Dimensionality Reduction: PCA and t-SNE',35,75),
    ('reading','Anomaly Detection Techniques',35,75),
    ('reading','Time Series Analysis and Forecasting',35,75),
    ('reading','Natural Language Processing with scikit-learn',35,75),
    ('exercise','Unsupervised and NLP Practice',50,100),
    ('reading','Introduction to Neural Networks with scikit-learn',35,75),
    ('reading','Model Explainability: SHAP and LIME',35,75),
    ('reading','ML Experiment Tracking with MLflow',35,75),
    ('reading','Model Deployment: Saving, Loading, and Serving',35,75),
    ('exercise','Explainability and Deployment Practice',50,100),
    ('reading','ML in Production: Drift Detection and Monitoring',35,75),
    ('reading','Fairness, Bias, and Responsible AI',35,75),
    ('reading','AutoML: H2O, AutoSklearn, and TPOT',35,75),
    ('reading','Building an ML Platform: Tools and Infrastructure',35,75),
    ('project','Capstone: Production ML System with Monitoring',60,150),
  ],

  'generative-ai': [
    ('reading','Introduction to Generative AI: GANs, VAEs, and LLMs',30,75),
    ('reading','Transformer Architecture: Attention and Self-Attention',35,75),
    ('reading','Large Language Models: GPT, Llama, and Mistral',35,75),
    ('reading','Tokenization and Embeddings for Text',35,75),
    ('exercise','Foundation Practice: LLM API Integration',50,100),
    ('reading','Prompt Engineering: Zero-Shot, Few-Shot, and CoT',35,75),
    ('reading','Structured Output and JSON Mode',35,75),
    ('reading','System Prompts and Conversation Management',35,75),
    ('reading','Hallucination: Causes, Detection, and Mitigation',35,75),
    ('exercise','Prompt Engineering Practice: AI Content Pipeline',50,100),
    ('reading','Fine-Tuning LLMs: When and How',35,75),
    ('reading','LoRA and QLoRA: Parameter-Efficient Fine-Tuning',35,75),
    ('reading','Instruction Tuning and RLHF',35,75),
    ('reading','Multimodal Models: Vision-Language and Audio',35,75),
    ('exercise','Fine-Tuning Assessment: Domain-Specific Model',50,100),
    ('reading','Text Embeddings: Semantic Search and Clustering',35,75),
    ('reading','Retrieval-Augmented Generation (RAG) Basics',35,75),
    ('reading','Vector Databases: Pinecone, Weaviate, Chroma',35,75),
    ('reading','Evaluation: BLEU, ROUGE, and LLM-as-Judge',35,75),
    ('project','Mid-Course Project: RAG-Powered Q&A System',60,150),
    ('reading','Building AI Applications with LangChain',35,75),
    ('reading','Image Generation: Stable Diffusion and DALL-E',35,75),
    ('reading','Code Generation Models: Copilot and Code Llama',35,75),
    ('reading','AI Agents: ReAct and Tool Use',35,75),
    ('exercise','AI Application Practice: Multi-Modal Chatbot',50,100),
    ('reading','Safety and Alignment: Guardrails and Red-Teaming',35,75),
    ('reading','Cost Optimisation: Model Selection and Caching',35,75),
    ('reading','Deployment: LLM Serving with vLLM and Ollama',35,75),
    ('reading','Observability for AI Applications',35,75),
    ('exercise','Deployment and Safety Practice',50,100),
    ('reading','AI Product Development: From Idea to Launch',35,75),
    ('reading','Legal and Ethical Considerations in Gen AI',35,75),
    ('reading','Emerging Models: Gemini, Claude, and Open-Source Trends',35,75),
    ('reading','Multimodal Workflows: Video, Audio, and Documents',35,75),
    ('project','Capstone: Production Generative AI Application',60,150),
  ],

  'rag': [
    ('reading','Introduction to RAG: Architecture and Use Cases',30,75),
    ('reading','Text Embeddings: Models and Dimensionality',35,75),
    ('reading','Vector Databases: Pinecone, Chroma, and Weaviate',35,75),
    ('reading','Document Loaders and Text Extraction',35,75),
    ('exercise','Foundation Practice: Basic Q&A RAG Pipeline',50,100),
    ('reading','Chunking Strategies: Fixed, Semantic, and Recursive',35,75),
    ('reading','Embedding Models: OpenAI, Cohere, and Open-Source',35,75),
    ('reading','Similarity Search: Cosine, Dot Product, and HNSW',35,75),
    ('reading','Building a RAG Pipeline with LangChain',35,75),
    ('exercise','Chunking and Retrieval Practice',50,100),
    ('reading','Query Preprocessing and Expansion',35,75),
    ('reading','Hybrid Search: BM25 + Dense Retrieval',35,75),
    ('reading','Cross-Encoder Reranking',35,75),
    ('reading','Contextual Compression and Filtering',35,75),
    ('exercise','Advanced Retrieval Practice',50,100),
    ('reading','RAG Evaluation: Faithfulness, Relevance, and Context',35,75),
    ('reading','The RAGAS Framework for Automated Evaluation',35,75),
    ('reading','LlamaIndex: An Alternative to LangChain for RAG',35,75),
    ('reading','Metadata Filtering and Structured Retrieval',35,75),
    ('project','Mid-Course Project: Enterprise Document Assistant',60,150),
    ('reading','Multi-Hop Retrieval and Complex Queries',35,75),
    ('reading','Self-Querying Retrieval and Routing',35,75),
    ('reading','GraphRAG: Knowledge Graphs and Neo4j',35,75),
    ('reading','Agentic RAG: Dynamic Retrieval Strategies',35,75),
    ('exercise','Advanced RAG Patterns Practice',50,100),
    ('reading','Production RAG: Scalability and Low Latency',35,75),
    ('reading','Data Ingestion Pipelines: Airflow and Prefect',35,75),
    ('reading','Multimodal RAG: Images, Tables, and PDFs',35,75),
    ('reading','Security: Access Control and PII Handling in RAG',35,75),
    ('exercise','Production and Security Practice',50,100),
    ('reading','Cost Optimisation: Caching and Batch Processing',35,75),
    ('reading','Streaming RAG Responses',35,75),
    ('reading','Monitoring RAG Pipelines in Production',35,75),
    ('reading','Future of RAG: Long Context vs Retrieval',35,75),
    ('project','Capstone: Production RAG Platform',60,150),
  ],

  'ai-agents': [
    ('reading','Introduction to AI Agents: Autonomy and Decision-Making',30,75),
    ('reading','Agent Architectures: Reactive, BDI, and LLM-Based',35,75),
    ('reading','The ReAct Framework: Reasoning + Acting',35,75),
    ('reading','Tool Use and Function Calling with LLMs',35,75),
    ('exercise','Foundation Practice: Build a Research Agent',50,100),
    ('reading','Memory Systems: Short-Term, Long-Term, and Episodic',35,75),
    ('reading','Planning and Goal Decomposition Strategies',35,75),
    ('reading','LangChain Agents: Tools, Chains, and Executors',35,75),
    ('reading','LangGraph: Stateful Agent Workflows',35,75),
    ('exercise','Memory and Planning Practice',50,100),
    ('reading','Multi-Agent Systems: Orchestration and Collaboration',35,75),
    ('reading','AutoGen: Conversational Multi-Agent Frameworks',35,75),
    ('reading','CrewAI: Role-Based Agent Teams',35,75),
    ('reading','Agent Communication Protocols and Schemas',35,75),
    ('exercise','Multi-Agent Practice: Research and Writing Team',50,100),
    ('reading','Custom Tools: APIs, Code Execution, and Browsers',35,75),
    ('reading','Web Browsing Agents with Playwright',35,75),
    ('reading','Code Generation and Execution Agents',35,75),
    ('reading','Human-in-the-Loop: Approval and Feedback Loops',35,75),
    ('project','Mid-Course Project: Autonomous Research Agent',60,150),
    ('reading','Agent Evaluation: Benchmarks and Success Metrics',35,75),
    ('reading','Error Handling and Agent Recovery',35,75),
    ('reading','Context Window Management and Summarisation',35,75),
    ('reading','Agent Security: Prompt Injection and Trust Boundaries',35,75),
    ('exercise','Evaluation and Reliability Practice',50,100),
    ('reading','Production Deployment of AI Agents',35,75),
    ('reading','Cost Optimisation: Reducing API Calls',35,75),
    ('reading','Observability: Logging and Tracing Agent Actions',35,75),
    ('reading','Testing AI Agents: Simulation and Regression',35,75),
    ('exercise','Production and Testing Practice',50,100),
    ('reading','Multimodal Agents: Vision and Document Understanding',35,75),
    ('reading','Autonomous Code Review Agents',35,75),
    ('reading','Domain-Specific Agents: Legal, Medical, Finance',35,75),
    ('reading','Future of AI Agents: AGI Pathways and Risks',35,75),
    ('project','Capstone: Production-Ready Multi-Agent System',60,150),
  ],

  'prompt-engineering': [
    ('reading','Introduction to Prompt Engineering: Why It Matters',20,50),
    ('reading','LLM Fundamentals: Tokens, Temperature, and Sampling',30,75),
    ('reading','Zero-Shot Prompting: Writing Effective Instructions',30,75),
    ('reading','Few-Shot Prompting: Examples and In-Context Learning',30,75),
    ('exercise','Foundation Practice: Prompt Design Challenges',50,100),
    ('reading','Chain-of-Thought Prompting: Step-by-Step Reasoning',30,75),
    ('reading','Tree-of-Thought and Graph-of-Thought Prompting',35,75),
    ('reading','Self-Consistency: Sampling Multiple Paths',30,75),
    ('reading','Least-to-Most Prompting for Complex Tasks',30,75),
    ('exercise','Reasoning Prompts Practice',50,100),
    ('reading','System Prompts: Persona, Tone, and Constraints',30,75),
    ('reading','Role Prompting and Character Consistency',30,75),
    ('reading','Instruction Hierarchy and Prompt Priority',30,75),
    ('reading','Prompt Templates and Variable Injection',30,75),
    ('exercise','System Prompt Design Practice',50,100),
    ('reading','Structured Output: JSON, XML, and Schema Enforcement',35,75),
    ('reading','Markdown and Format Control in Outputs',30,75),
    ('reading','Prompt Chaining: Connecting Multiple Steps',35,75),
    ('reading','Retrieval-Augmented Prompting',35,75),
    ('project','Mid-Course Project: Prompt-Driven Content Pipeline',60,150),
    ('reading','Evaluation: Measuring Prompt Quality and Consistency',35,75),
    ('reading','A/B Testing Prompts: Systematic Improvement',35,75),
    ('reading','Prompt Injection: Attack Vectors and Defences',35,75),
    ('reading','Jailbreaking and Safety Considerations',30,75),
    ('exercise','Evaluation and Safety Practice',50,100),
    ('reading','Code Generation Prompts: Best Practices',35,75),
    ('reading','Data Extraction and Transformation Prompts',35,75),
    ('reading','Summarisation Prompts for Long Documents',30,75),
    ('reading','Multi-Modal Prompting: Images and Audio',35,75),
    ('exercise','Domain-Specific Prompt Practice',50,100),
    ('reading','Cost Optimisation: Token Reduction Strategies',30,75),
    ('reading','Model-Specific Tuning: Claude, GPT-4, Gemini',35,75),
    ('reading','Prompt Management: Version Control and Libraries',30,75),
    ('reading','The Future of Prompting: DSPy and Automated Optimisation',35,75),
    ('project','Capstone: Prompt Library for Production AI System',60,150),
  ],

  'mlops': [
    ('reading','Introduction to MLOps: Principles and the ML Lifecycle',30,75),
    ('reading','Experiment Tracking with MLflow',35,75),
    ('reading','Data Versioning with DVC',35,75),
    ('reading','Feature Stores: Feast and Tecton',35,75),
    ('exercise','Foundation Practice: ML Experiment Pipeline',50,100),
    ('reading','Model Training Pipelines with Kubeflow Pipelines',35,75),
    ('reading','Orchestrating ML Workflows with Airflow and Prefect',35,75),
    ('reading','Hyperparameter Optimisation with Optuna',35,75),
    ('reading','Distributed Training: Horovod and PyTorch DDP',35,75),
    ('exercise','Training Pipeline Practice: AutoML with Optuna',50,100),
    ('reading','Model Packaging: Docker, ONNX, and Serialisation',35,75),
    ('reading','Model Registry: MLflow, Vertex AI, and SageMaker',35,75),
    ('reading','REST API Serving with FastAPI and TorchServe',35,75),
    ('reading','Batch Inference vs Online Inference',35,75),
    ('exercise','Serving Practice: Model API with Autoscaling',50,100),
    ('reading','Model Monitoring: Data Drift and Concept Drift',35,75),
    ('reading','Evidently AI: Monitoring Reports and Test Suites',35,75),
    ('reading','A/B Testing and Shadow Deployment',35,75),
    ('reading','Feedback Loops and Continuous Training',35,75),
    ('project','Mid-Course Project: End-to-End MLOps Pipeline',60,150),
    ('reading','CI/CD for ML: GitHub Actions and DVC Pipelines',35,75),
    ('reading','Infrastructure as Code for ML: Terraform + SageMaker',35,75),
    ('reading','Kubernetes for ML: KServe and Seldon Core',35,75),
    ('reading','GPU Management and Resource Scheduling',35,75),
    ('exercise','CI/CD and Infrastructure Practice',50,100),
    ('reading','Model Explainability in Production: SHAP and LIME',35,75),
    ('reading','Fairness Monitoring and Bias Detection',35,75),
    ('reading','Cost Optimisation: Spot Instances and Model Compression',35,75),
    ('reading','Security: Model Theft and Adversarial Attacks',35,75),
    ('exercise','Governance and Security Practice',50,100),
    ('reading','LLMOps: Fine-Tuning, Evaluation, and Deployment at Scale',35,75),
    ('reading','Vector Database Management and Embedding Pipelines',35,75),
    ('reading','Observability: Prometheus, Grafana, and ML Metrics',35,75),
    ('reading','Building an Internal ML Platform',35,75),
    ('project','Capstone: Production MLOps Platform',60,150),
  ],

  # ════════════════════════════════════════════════════════════════
  # DATABASES
  # ════════════════════════════════════════════════════════════════

  'postgresql': [
    ('reading','Introduction to PostgreSQL: Architecture and Installation',30,75),
    ('reading','Data Types: Numeric, Text, JSON, Arrays, and UUID',35,75),
    ('reading','Tables, Constraints, and Relationships',35,75),
    ('reading','Basic SQL: SELECT, INSERT, UPDATE, DELETE',30,75),
    ('exercise','Foundation Practice: Schema Design and Basic Queries',50,100),
    ('reading','Joins: Inner, Left, Right, Full, and Cross',35,75),
    ('reading','Aggregations: GROUP BY, HAVING, and Window Functions',35,75),
    ('reading','Subqueries, CTEs, and Recursive Queries',35,75),
    ('reading','Views and Materialised Views',35,75),
    ('exercise','Advanced Query Practice: Analytics Dashboard',50,100),
    ('reading','Indexes: B-Tree, Hash, GIN, GiST, and BRIN',35,75),
    ('reading','Index Design: Partial, Composite, and Expression Indexes',35,75),
    ('reading','EXPLAIN ANALYZE: Reading and Optimising Query Plans',35,75),
    ('reading','Table Partitioning: Range, List, and Hash',35,75),
    ('exercise','Indexing and Query Optimisation Practice',50,100),
    ('reading','Transactions: ACID, Isolation Levels, and Locking',35,75),
    ('reading','MVCC: How PostgreSQL Manages Concurrency',35,75),
    ('reading','Deadlocks: Detection, Prevention, and Resolution',35,75),
    ('reading','Full-Text Search with tsvector and tsquery',35,75),
    ('project','Mid-Course Project: High-Performance Analytics DB',60,150),
    ('reading','JSONB: Querying, Indexing, and Performance',35,75),
    ('reading','Stored Procedures and PL/pgSQL Functions',35,75),
    ('reading','Triggers: Auditing and Data Integrity',35,75),
    ('reading','pg_cron and Scheduled Maintenance Jobs',30,75),
    ('exercise','Advanced Features Practice: Audit System',50,100),
    ('reading','Replication: Streaming, Logical, and Slot-Based',35,75),
    ('reading','High Availability with Patroni and pg_auto_failover',35,75),
    ('reading','Connection Pooling with PgBouncer',35,75),
    ('reading','Backup and Recovery: pg_dump, pg_basebackup, PITR',35,75),
    ('exercise','Replication and HA Practice',50,100),
    ('reading','PostgreSQL Security: Roles, Row-Level Security, SSL',35,75),
    ('reading','Vacuum, Analyse, and Autovacuum Tuning',35,75),
    ('reading','PostgreSQL with Docker and Kubernetes',30,75),
    ('reading','Extensions: PostGIS, TimescaleDB, and pgvector',35,75),
    ('project','Capstone: Production PostgreSQL Cluster',60,150),
  ],

  'mongodb': [
    ('reading','Introduction to MongoDB: Document Model and Use Cases',30,75),
    ('reading','BSON Types, Documents, and Collections',30,75),
    ('reading','CRUD Operations: insertOne, find, updateOne, deleteOne',30,75),
    ('reading','Query Operators: Comparison, Logical, and Array',35,75),
    ('exercise','Foundation Practice: Product Catalogue with MongoDB',50,100),
    ('reading','Schema Design: Embedding vs Referencing',35,75),
    ('reading','Data Modelling Patterns: Bucket, Subset, and Computed',35,75),
    ('reading','Indexes: Single Field, Compound, and Multikey',35,75),
    ('reading','Text Indexes and Full-Text Search',35,75),
    ('exercise','Schema Design Practice: Social Network Model',50,100),
    ('reading','Aggregation Pipeline: $match, $group, $lookup, $project',35,75),
    ('reading','Aggregation: $unwind, $bucket, $facet, and $merge',35,75),
    ('reading','Atlas Search: Lucene-Powered Full-Text Search',35,75),
    ('reading','Atlas Vector Search: Semantic Search with Embeddings',35,75),
    ('exercise','Aggregation Pipeline Practice: Analytics Report',50,100),
    ('reading','Transactions: Multi-Document ACID Transactions',35,75),
    ('reading','Change Streams: Real-Time Data Monitoring',35,75),
    ('reading','Validation with JSON Schema',35,75),
    ('reading','Time Series Collections',35,75),
    ('project','Mid-Course Project: Real-Time Analytics Platform',60,150),
    ('reading','Replication: Replica Sets and Elections',35,75),
    ('reading','Sharding: Architecture, Keys, and Zone Sharding',35,75),
    ('reading','Atlas Global Clusters and Multi-Cloud',35,75),
    ('reading','Connection Pooling and Driver Configuration',35,75),
    ('exercise','Replication and Sharding Practice',50,100),
    ('reading','Security: Authentication, RBAC, and Field-Level Encryption',35,75),
    ('reading','Performance Tuning: Explain Plans and Index Strategies',35,75),
    ('reading','Backup and Restore: mongodump and Atlas Backups',30,75),
    ('reading','MongoDB with Node.js: Mongoose and Native Driver',35,75),
    ('exercise','Security and Performance Practice',50,100),
    ('reading','MongoDB with Python: PyMongo and Motor',35,75),
    ('reading','Atlas Data Federation: Querying S3 and Atlas',35,75),
    ('reading','Atlas App Services: Triggers and Serverless Functions',35,75),
    ('reading','Migrating from RDBMS to MongoDB',35,75),
    ('project','Capstone: Production MongoDB Atlas Application',60,150),
  ],

  # ════════════════════════════════════════════════════════════════
  # SOFTWARE ENGINEERING
  # ════════════════════════════════════════════════════════════════

  'dsa': [
    ('reading','Introduction to DSA: Complexity Analysis and Big-O',30,75),
    ('reading','Arrays: Operations, Sliding Window, and Two Pointers',35,75),
    ('reading','Strings: Manipulation, Hashing, and Pattern Matching',35,75),
    ('reading','Hash Maps and Hash Sets: Frequency and Lookup Problems',35,75),
    ('exercise','Foundation Practice: Array and String Challenges',50,100),
    ('reading','Stacks: Implementation, Monotonic Stack, and Applications',35,75),
    ('reading','Queues, Deques, and Priority Queues',35,75),
    ('reading','Linked Lists: Singly, Doubly, and Cycle Detection',35,75),
    ('reading','Recursion and the Recursion Tree Method',35,75),
    ('exercise','Linear Data Structures Practice',50,100),
    ('reading','Binary Search: Standard, Rotated Arrays, and Search Space',35,75),
    ('reading','Sorting Algorithms: Merge Sort, Quick Sort, Heap Sort',35,75),
    ('reading','Trees: Binary Trees, Traversals, and BST',35,75),
    ('reading','Tree Problems: LCA, Diameter, and Path Sum',35,75),
    ('exercise','Binary Search and Tree Practice',50,100),
    ('reading','Heaps and Priority Queues: Top-K and Median',35,75),
    ('reading','Tries: Prefix Trees for String Problems',35,75),
    ('reading','Graphs: Representation, BFS, and DFS',35,75),
    ('reading','Graph Algorithms: Dijkstra, Bellman-Ford, and Prim',35,75),
    ('project','Mid-Course Project: Graph-Based Problem Set',60,150),
    ('reading','Topological Sort and Cycle Detection in Graphs',35,75),
    ('reading','Union-Find: Disjoint Set Union',35,75),
    ('reading','Dynamic Programming: Memoization and Tabulation',35,75),
    ('reading','DP Patterns: Knapsack, LCS, and Coin Change',35,75),
    ('exercise','Graph and DP Practice',50,100),
    ('reading','DP on Trees and Strings',35,75),
    ('reading','Greedy Algorithms: Activity Selection and Huffman',35,75),
    ('reading','Backtracking: Permutations, Subsets, and N-Queens',35,75),
    ('reading','Bit Manipulation: XOR, Masks, and Bit Tricks',35,75),
    ('exercise','Advanced Algorithms Practice',50,100),
    ('reading','Interval Problems: Merge, Insert, and Meeting Rooms',35,75),
    ('reading','Math for DSA: GCD, Primes, and Modular Arithmetic',35,75),
    ('reading','System Design for Interviews: Trade-offs and Estimates',35,75),
    ('reading','Mock Interview Strategies and Time Management',30,75),
    ('project','Capstone: 30-Problem Interview Preparation Set',60,150),
  ],

  'system-design': [
    ('reading','Introduction to System Design: Scale, Trade-offs, and Process',30,75),
    ('reading','Estimation: Back-of-the-Envelope Calculations',30,75),
    ('reading','CAP Theorem and PACELC',35,75),
    ('reading','Load Balancing: Algorithms, L4 vs L7, and Health Checks',35,75),
    ('exercise','Foundation Practice: Design a URL Shortener',50,100),
    ('reading','Caching: Strategies, Eviction Policies, and Redis',35,75),
    ('reading','Database Selection: SQL vs NoSQL Decision Framework',35,75),
    ('reading','Database Scaling: Sharding, Replication, and Federation',35,75),
    ('reading','Consistent Hashing: Distributed Key Partitioning',35,75),
    ('exercise','Caching and Database Practice: Design a Cache System',50,100),
    ('reading','Message Queues: Kafka, RabbitMQ, and SQS Trade-offs',35,75),
    ('reading','Event-Driven Architecture and Event Sourcing',35,75),
    ('reading','API Design: REST, GraphQL, and gRPC at Scale',35,75),
    ('reading','CDN: Edge Caching and Content Delivery',35,75),
    ('exercise','Messaging and API Practice: Design a Notification System',50,100),
    ('reading','Design a Social Feed: Fan-Out on Write vs Read',35,75),
    ('reading','Design a Search Engine: Inverted Index and Ranking',35,75),
    ('reading','Design a Video Streaming Platform',35,75),
    ('reading','Design a Ride-Sharing System',35,75),
    ('project','Mid-Course Project: Design Twitter/X at Scale',60,150),
    ('reading','Rate Limiting: Token Bucket and Sliding Window',35,75),
    ('reading','Service Discovery and DNS in Microservices',35,75),
    ('reading','Distributed Locks and Leader Election',35,75),
    ('reading','Distributed Transactions: 2PC and Saga',35,75),
    ('exercise','Distributed Systems Practice: Design a Payment System',50,100),
    ('reading','Monitoring and Observability at Scale',35,75),
    ('reading','Disaster Recovery: RPO, RTO, and Multi-Region',35,75),
    ('reading','Security at Scale: Zero-Trust and DDoS Mitigation',35,75),
    ('reading','Design a Key-Value Store from Scratch',35,75),
    ('exercise','Resilience and Security Practice',50,100),
    ('reading','Design a Distributed File System: HDFS and GFS',35,75),
    ('reading','Design a Recommendation System',35,75),
    ('reading','Design a Real-Time Collaborative Editor',35,75),
    ('reading','Interview Framework: How to Structure Any Design',30,75),
    ('project','Capstone: Design an End-to-End SaaS Platform',60,150),
  ],

  # ════════════════════════════════════════════════════════════════
  # MOBILE
  # ════════════════════════════════════════════════════════════════

  'react-native': [
    ('reading','Introduction to React Native and Expo',30,75),
    ('reading','Core Components: View, Text, Image, and ScrollView',30,75),
    ('reading','Styling with StyleSheet: Flexbox on Mobile',35,75),
    ('reading','Handling Touch and Gestures',30,75),
    ('exercise','Foundation Practice: Profile Card App',50,100),
    ('reading','State Management with useState and useContext',35,75),
    ('reading','Navigation with React Navigation v7',35,75),
    ('reading','Stack, Tab, and Drawer Navigators',35,75),
    ('reading','Passing Data Between Screens',30,75),
    ('exercise','Navigation Practice: Multi-Screen Task App',50,100),
    ('reading','FlatList and SectionList: Performant Lists',35,75),
    ('reading','TextInput, Forms, and Keyboard Handling',35,75),
    ('reading','Fetching Data with the Fetch API and Axios',35,75),
    ('reading','Async Storage and Secure Store',35,75),
    ('exercise','Data and Forms Practice: Contact Manager',50,100),
    ('reading','Camera, Image Picker, and Media Library',35,75),
    ('reading','Maps with react-native-maps',35,75),
    ('reading','Push Notifications with Expo Notifications',35,75),
    ('reading','Background Tasks and Location Services',35,75),
    ('project','Mid-Course Project: Location-Based Mobile App',60,150),
    ('reading','Animations with Reanimated 3 and Gesture Handler',35,75),
    ('reading','State Management at Scale with Zustand',35,75),
    ('reading','React Query for Mobile: Caching and Sync',35,75),
    ('reading','Authentication: OAuth, Biometrics, and JWT',35,75),
    ('exercise','Animations and State Practice',50,100),
    ('reading','TypeScript with React Native',35,75),
    ('reading','Testing: Jest and React Native Testing Library',35,75),
    ('reading','Performance: Hermes Engine and Bundle Optimisation',35,75),
    ('reading','Native Modules: Bridging JavaScript and Native Code',35,75),
    ('exercise','Testing and Performance Practice',50,100),
    ('reading','Expo EAS Build: Cloud Build Service',30,75),
    ('reading','App Store and Google Play Submission Process',30,75),
    ('reading','OTA Updates with Expo Updates',30,75),
    ('reading','Crash Reporting and Analytics with Sentry',30,75),
    ('project','Capstone: Production React Native Application',60,150),
  ],

  'flutter': [
    ('reading','Introduction to Flutter and Dart Programming Language',30,75),
    ('reading','Dart Fundamentals: Types, Functions, and OOP',35,75),
    ('reading','Flutter Architecture: Widgets, Trees, and Rendering',35,75),
    ('reading','Core Widgets: Container, Row, Column, and Stack',30,75),
    ('exercise','Foundation Practice: Flutter UI Component Library',50,100),
    ('reading','Material Design 3 and Cupertino Widgets',35,75),
    ('reading','Stateless vs Stateful Widgets and setState',35,75),
    ('reading','BuildContext and Widget Lifecycle',35,75),
    ('reading','Custom Widgets and Composition Patterns',35,75),
    ('exercise','Widget Practice: Dashboard UI',50,100),
    ('reading','Navigation 2.0 and GoRouter',35,75),
    ('reading','Forms, Validation, and TextEditingController',35,75),
    ('reading','HTTP Requests with dio and http Package',35,75),
    ('reading','JSON Serialisation with json_serializable',35,75),
    ('exercise','Navigation and Data Practice: News Reader App',50,100),
    ('reading','State Management with Provider',35,75),
    ('reading','Riverpod: Modern State Management for Flutter',35,75),
    ('reading','BLoC Pattern: Business Logic Component',35,75),
    ('reading','GetX: All-in-One Solution',35,75),
    ('project','Mid-Course Project: Weather App with Riverpod',60,150),
    ('reading','Animations: AnimatedWidget, AnimationController',35,75),
    ('reading','Implicit Animations and Hero Transitions',35,75),
    ('reading','Custom Painters and Canvas API',35,75),
    ('reading','Flutter Maps and Geolocation',35,75),
    ('exercise','Animations and Graphics Practice',50,100),
    ('reading','Firebase Integration: Auth, Firestore, and Storage',35,75),
    ('reading','Push Notifications with Firebase Cloud Messaging',35,75),
    ('reading','Local Storage: Hive and SharedPreferences',35,75),
    ('reading','Platform Channels: Accessing Native APIs',35,75),
    ('exercise','Firebase and Platform Practice',50,100),
    ('reading','Testing: Widget Tests, Integration Tests, and Mocks',35,75),
    ('reading','Performance: const Widgets and Rendering Optimisation',35,75),
    ('reading','Flavors: Multiple App Variants from One Codebase',35,75),
    ('reading','Deploying to App Store and Google Play with Fastlane',30,75),
    ('project','Capstone: Production Flutter Application',60,150),
  ],
}
