"use client";

import { useState } from "react";
import type { GeneratedCourse, IntakeProfile } from "@/lib/types";
import { OnboardingForm } from "@/components/OnboardingForm";
import { ModuleViewer } from "@/components/ModuleViewer";

export function CourseBuilderApp() {
  const [loading, setLoading] = useState(false);
  const [course, setCourse] = useState<GeneratedCourse | null>(null);
  const [error, setError] = useState<string | null>(null);
  async function generateCourse(profile: IntakeProfile) {
    setLoading(true);
    setError(null);

    try {
      const response = await fetch("/api/course/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          userId: "demo-user",
          profile,
        }),
      });

      if (!response.ok) {
        const details = await response.text();
        throw new Error(`Failed to generate course: ${details}`);
      }

      const payload = (await response.json()) as {
        source: "cache" | "generated";
        generatedCourse: GeneratedCourse;
      };
      setCourse(payload.generatedCourse);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unexpected error");
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="app-shell">
      <h1 className="hero-title">AI Upskilling Platform</h1>
      <p className="hero-subtitle">
        Personalized learning paths generated by modular AI agents with
        iterative quality validation.
      </p>

      <section className="spaced">
        <OnboardingForm onGenerate={generateCourse} loading={loading} />
      </section>

      {error ? (
        <p className="error-banner">{error}</p>
      ) : null}

      {course ? (
        <section className="spaced">
          <article className="panel">
            <header className="panel-header">
              <h2>{course.learningPath.title}</h2>
              <p>{course.learningPath.reasoning}</p>
            </header>
            <div className="chips">
              <span className="chip">Level: {course.profile.experience_level}</span>
              <span className="chip">Goal: {course.profile.goal}</span>
              <span className="chip">Quality: {course.qualityScore}/100</span>
              <span className="chip">Model: {course.metadata.model}</span>
            </div>
          </article>
          <ModuleViewer module={course.modules[0]} />
        </section>
      ) : null}
    </main>
  );
}
