import type { CourseAnalogies } from '../engine'

const analogies: CourseAnalogies = {
  courseSlug: 'pytorch-deep-learning',
  courseTitle: 'PyTorch Deep Learning',
  concepts: [
    {
      id: 'tensors',
      name: 'Tensors',
      cricket:     'A scorecard that can hold runs, wickets, overs, and strike rates all at once — multi-dimensional data in a single structured sheet.',
      gaming:      'A 3D game world array storing X/Y/Z coordinates, health, and damage values for every entity in the scene simultaneously.',
      music:       'A multi-track recording session where each axis is a track, a beat, and an EQ band — all the audio data in one unified grid.',
      photography: 'An image stored as three stacked grids (R, G, B channels) where every pixel has three intensity values — that grid is a tensor.',
      travel:      'A travel matrix: rows = destinations, columns = dates, depth = transport modes — all options in one compact lookup cube.',
      movies:      'A scene breakdown: each frame is a 2D grid of pixels, stacked across time, giving you a 3D tensor of the entire film.',
      fitness:     'A training log where rows = days, columns = exercises, and a third axis = reps/sets/weight — every workout stat in one block.',
      chess:       'An 8×8 board tensor where each square holds piece type, colour, and threat level as separate values — the whole game state in one structure.',
      cooking:     'A recipe matrix: rows = dishes, columns = ingredients, depth = quantities, prep time, calories — one unified table for the entire menu.',
      finance:     'A portfolio matrix with rows = assets, columns = dates, and depth = price, volume, volatility — every market dimension accessible at once.',
      business:    'A KPI cube: products × regions × months, giving you revenue, margin, and churn in a single queryable structure.',
      sports:      'A match stats tensor: players × game minutes × metrics (speed, distance, passes) — the full performance data in one multi-dim array.',
    },
    {
      id: 'autograd',
      name: 'Autograd & Backpropagation',
      cricket:     'The coach who watches a dismissal, traces exactly which shot went wrong, and tells each part of the technique how much to adjust.',
      gaming:      'The game\'s post-match replay that pinpoints the precise decision that lost you the round and scores each choice by how costly it was.',
      music:       'A producer listening to a rough mix, identifying exactly which instrument is too loud, by how much, and sending precise EQ corrections to each track.',
      photography: 'Reviewing a blurry photo, measuring how out-of-focus it is, then computing exactly how many millimetres to adjust focus and aperture.',
      travel:      'A navigation app that, after reaching the wrong destination, calculates turn by turn where the route went wrong and scores each decision.',
      movies:      'A director\'s cut session where every scene is graded by how much it reduced tension, and editors are told exactly how many seconds to trim each one.',
      fitness:     'A physio who watches a faulty squat, measures the knee-cave angle, and gives each muscle precise instructions on how much more to engage.',
      chess:       'Post-game engine analysis that assigns a centipawn loss to every move and tells you exactly how much each decision hurt your position.',
      cooking:     'A head chef tasting a dish, identifying the dish is too salty by 2g, and tracing which step (the sauce reduction) introduced the excess.',
      finance:     'A risk attribution model that, after a portfolio loss, tells each position exactly how many basis points of drawdown it contributed.',
      business:    'A root-cause analysis that traces a missed revenue target back through each team\'s contribution and scores who needs to adjust by how much.',
      sports:      'A coaching app that reviews match footage, finds the missed tackle, and tells each player\'s positioning how many metres off they were.',
    },
    {
      id: 'neural-network-layers',
      name: 'Neural Network Layers',
      cricket:     'Specialist coaches stacked in sequence — the batting coach refines grip, the footwork coach builds on that, the shot-selection coach finishes it.',
      gaming:      'A skill tree where each tier builds on the last: basic movement unlocks dodging which unlocks combo attacks — layered complexity.',
      music:       'Arrangement layers: rhythm section → harmony → lead melody → effects processing. Each layer refines what the layer below produced.',
      photography: 'The editing pipeline: RAW develop → exposure correction → colour grade → sharpening → final export. Each stage transforms the image further.',
      travel:      'Booking stages: find destination → choose flights → book hotel → plan activities → arrange transfers. Each layer builds on confirmed decisions.',
      movies:      'Post-production pipeline: rough cut → colour grade → sound mix → VFX compositing → final master. Every stage specialises and refines.',
      fitness:     'A periodised training plan: foundation mobility → strength base → power development → sport-specific skill. Each phase stacks on the last.',
      chess:       'Opening → middlegame → endgame strategy. Knowledge from each phase feeds the next; you cannot play a good endgame without a solid opening foundation.',
      cooking:     'French mother sauces: you make a roux, add stock, build a velouté, then add cream for a suprême. Each layer transforms what came before.',
      finance:     'Analysis pipeline: macro screening → sector filter → fundamental analysis → technical timing → position sizing. Each layer narrows and refines.',
      business:    'Go-to-market stack: awareness → consideration → conversion → retention → advocacy. Each stage converts output from the one before.',
      sports:      'Athletic development layers: aerobic base → strength → speed → agility → sport skill. You cannot skip a layer and sustain elite performance.',
    },
    {
      id: 'loss-functions',
      name: 'Loss Functions',
      cricket:     'The scoreboard gap — the raw number of runs behind the target. Your whole strategy revolves around minimising this gap over the innings.',
      gaming:      'The health bar or score gap: how far below the high score you are. Every action is judged by how much it closes that gap.',
      music:       'The pitch deviation meter in a tuner app — it tells you exactly how many cents sharp or flat you are so you know how much to correct.',
      photography: 'The histogram clipping warning: it quantifies how many pixels are blown out or crushed, giving you a precise target to bring under control.',
      travel:      'The distance from your destination: every route choice is scored by how much it reduces the remaining kilometres to travel.',
      movies:      'A test-screening score: audience ratings quantify how far the current cut is from the desired emotional impact, guiding every editorial decision.',
      fitness:     'The gap between your current lifts and your target: 10kg short on bench press is the loss; training decisions are made to reduce that gap.',
      chess:       'Centipawn evaluation: a number saying your position is −150 centipawns. Every candidate move is scored by how much it improves that value.',
      cooking:     'The deviation from the target flavour profile — how far from balanced the dish is, measured by tasting notes: 2g too salty, 5ml acid short.',
      finance:     'Portfolio tracking error vs a benchmark: the exact number of basis points you underperformed, driving every rebalancing decision.',
      business:    'The revenue gap to plan: if target is £1M and actual is £820K, that £180K gap is the loss that focuses every quarterly strategy.',
      sports:      'The points or seconds deficit in a race: every training session, tactic, and substitution is scored by how much it closes the gap to first place.',
    },
    {
      id: 'optimizers',
      name: 'Optimizers (SGD, Adam)',
      cricket:     'The batting coach\'s adaptive strategy: SGD is straightforward — same adjustment every over. Adam remembers which shots went wrong earlier and adapts the correction size.',
      gaming:      'SGD is running the same strategy every match and grinding. Adam is an adaptive AI controller that adjusts sensitivity for each input based on recent match history.',
      music:       'SGD is a metronome — steady, fixed tempo adjustments. Adam is a live drummer who speeds up passages that rush and slows phrases that drag, self-correcting in real time.',
      photography: 'SGD is fixed manual exposure adjustments. Adam is Auto-ISO with scene memory — it takes smaller steps in bright scenes and larger steps in dark ones based on recent shots.',
      travel:      'SGD is Google Maps taking the fastest route every time. Adam is a seasoned traveller who remembers last week\'s traffic patterns and adjusts route confidence per road segment.',
      movies:      'SGD is a director giving the same note after every take. Adam is a director who tracks which aspects of performance improved last time and scales feedback accordingly.',
      fitness:     'SGD is adding 5kg to the bar every session regardless. Adam is a smart progressive overload algorithm that scales the increment based on recent rate of adaptation.',
      chess:       'SGD is always moving the same piece type. Adam is a time-management system that allocates more clock to decisions where you\'ve historically made mistakes.',
      cooking:     'SGD is adding a fixed pinch of salt every time. Adam is an experienced chef who adjusts seasoning amounts based on how salty previous dishes turned out.',
      finance:     'SGD is dollar-cost averaging a fixed amount. Adam is a dynamic allocation strategy that adjusts contribution size based on recent volatility of each asset.',
      business:    'SGD is running the same weekly ad spend. Adam is a performance marketing tool that adjusts bids per keyword based on its recent conversion history.',
      sports:      'SGD is a fixed training load every week. Adam is a periodised programme that modulates volume and intensity per exercise based on your recent adaptation rate.',
    },
    {
      id: 'training-loop',
      name: 'The Training Loop',
      cricket:     'Net practice: bowl → assess where the delivery landed → adjust run-up → bowl again. Repeat hundreds of times until muscle memory is calibrated.',
      gaming:      'A grind session: play a level, see where you die, adjust your loadout and route, play again. Each death is one training step; mastery is thousands of steps.',
      music:       'Practising a difficult passage: play → hear the wrong note → adjust finger placement → play again. The loop runs until the phrase is clean.',
      photography: 'A day of bracketed exposures: shoot → check histogram → adjust settings → shoot again. Each cycle the exposure converges toward perfect.',
      travel:      'Trip planning iteration: draft itinerary → identify conflicts → reschedule → validate again. You loop until the itinerary has no clashes.',
      movies:      'Re-shoots and assembly cuts: film scene → screen it → note what feels wrong → re-film with adjustments → screen again. Each pass refines the story.',
      fitness:     'A training block: attempt a PR → assess form breakdown → correct weaknesses → attempt again next session. Progress is the accumulation of loops.',
      chess:       'Puzzle training: attempt a tactic → see the solution → understand the pattern → attempt the next puzzle. Pattern recognition grows with each loop.',
      cooking:     'Recipe development: cook a batch → taste and note flaws → adjust ratios → cook again. Each batch is one epoch; the recipe converges over iterations.',
      finance:     'Backtesting: run strategy on historical data → measure performance → adjust parameters → re-run. Each iteration tunes the strategy toward better risk-adjusted returns.',
      business:    'Build-measure-learn: launch an MVP → analyse user behaviour → identify friction → iterate the product → launch again. Each sprint is a training epoch.',
      sports:      'Pre-season camp: run drills → analyse video → correct technique → repeat. Coaches loop players through scenarios until the response is automatic.',
    },
    {
      id: 'overfitting',
      name: 'Overfitting',
      cricket:     'A bowler who practises only on one specific pitch and one batter\'s weak spot. They dominate in the nets but get hit all over the ground in a real match.',
      gaming:      'A player who memorises one map\'s spawn points perfectly but is completely lost the moment a new map is added to the rotation.',
      music:       'A musician who can only perform a song in the exact key and tempo of the recording they learned from — change either by a semitone and they fall apart.',
      photography: 'Editing one photo to pixel-perfection with a very specific preset, then applying it to every other shot only to find it ruins them all.',
      travel:      'Planning so specifically for one trip that your packing list, adapters, and translation notes are useless the moment you visit a different country.',
      movies:      'A screenplay written so tightly around one actor\'s specific mannerisms that no other casting works — the role cannot be recast.',
      fitness:     'Training exclusively on a machine with fixed movement paths. Your numbers look great in the gym but the strength doesn\'t transfer to real sports or daily life.',
      chess:       'Memorising an opening line 20 moves deep but having no positional understanding — the moment your opponent deviates on move 4, you are lost.',
      cooking:     'Perfecting a dish only with one brand of tomato. Switch to a different brand and the recipe falls apart because you tuned every step to that specific ingredient.',
      finance:     'A trading model trained only on 2010–2020 bull-market data. It performs brilliantly in backtests and catastrophically the moment volatility returns.',
      business:    'A startup whose growth playbook only works for the specific audience in one city during one season — the moment they try to expand, it breaks down.',
      sports:      'A tennis player who rehearses returns against one training partner\'s serve exclusively. They ace those sessions but struggle against any variation in style.',
    },
    {
      id: 'regularization',
      name: 'Regularization (Dropout, L2)',
      cricket:     'Fielding restrictions: you cannot pack all fielders in one spot. The rule forces the team to distribute coverage, building general defensive skill.',
      gaming:      'Permadeath or ironman modes: knowing each character can die permanently forces you to build flexible strategies rather than relying on one overpowered unit.',
      music:       'Practising without a metronome or with changed time signatures: it forces you to internalise rhythm rather than depending on an external crutch.',
      photography: 'Shooting with a prime lens only (no zoom): forces you to move your feet and compose more creatively, developing adaptable compositional instincts.',
      travel:      'Travelling without a detailed itinerary for one day: forces you to navigate and adapt on the spot, building genuine problem-solving confidence.',
      movies:      'A script limit on dialogue: writers must convey emotion through action and visual storytelling rather than leaning on exposition as a crutch.',
      fitness:     'Unilateral training (one arm/leg at a time): exposes and corrects imbalances you masked with bilateral lifts — general strength improves as a result.',
      chess:       'Playing blindfold chess: you cannot rely on visually scanning the board, so you are forced to build a robust internal model of piece positions.',
      cooking:     'Cooking a dish with only five ingredients: prevents relying on complex sauces to rescue poor technique and forces mastery of fundamentals.',
      finance:     'A maximum position size rule (e.g. no single stock over 5%): prevents over-concentration on a winner and forces diversified, robust portfolio construction.',
      business:    'A headcount freeze: forces teams to solve problems with existing resources, developing efficient processes instead of defaulting to "hire more people."',
      sports:      'Training in altitude or with weighted vests: adds difficulty that forces adaptation, so the athlete is stronger in normal conditions than they\'d otherwise be.',
    },
    {
      id: 'cnns',
      name: 'Convolutional Neural Networks',
      cricket:     'A fielder who reads the ball\'s seam position, swing, and release point in the first few metres — local pattern detection at each stage of flight.',
      gaming:      'A detection system that scans each screen region for enemy silhouettes, muzzle flashes, and health-bar colours — local feature scanning across the game frame.',
      music:       'Identifying a chord from its frequency fingerprint — the model scans small windows of the waveform, recognises intervals, and assembles them into a chord name.',
      photography: 'Edge detection: scanning each small neighbourhood of pixels for sharp brightness changes that indicate object boundaries, corners, and textures.',
      travel:      'Reading road signs while driving: your eye scans a small window of the visual field, recognises letters and shapes locally, then assembles meaning.',
      movies:      'Shot recognition: a CNN identifies close-up, wide shot, or tracking shot by scanning local frame regions for focal length and movement cues.',
      fitness:     'Form analysis: a camera scans your joint angles frame by frame — small local regions (knee, hip, ankle) — and assembles a full form-quality score.',
      chess:       'Tactical pattern recognition: scanning 3×3 windows of the board to detect forks, pins, or skewers — local piece relationships that add up to tactical awareness.',
      cooking:     'Identifying doneness by colour: scanning the surface texture of meat locally — sear colour, grill marks, moisture sheen — to assess overall cook quality.',
      finance:     'Chart pattern recognition: scanning small windows of price/volume history to detect head-and-shoulders, flags, or double bottoms as local features.',
      business:    'Customer sentiment scanning: a model reads every support ticket word-window for negative language clusters before assembling an overall churn-risk score.',
      sports:      'Player tracking: cameras scan small image patches for jersey numbers and limb positions, assembling them into full player-movement heat maps.',
    },
    {
      id: 'transfer-learning',
      name: 'Transfer Learning',
      cricket:     'A seasoned Test cricketer moving to T20: they bring years of shot-making skill and only need a short adaptation period to adjust timing and shot selection.',
      gaming:      'A top-tier MOBA player picking up a new hero: the strategic map awareness and team-fight instincts transfer instantly; only the new kit needs learning.',
      music:       'A classically trained pianist learning jazz: music theory, finger technique, and ear training all transfer — they just need to add improvisation vocabulary.',
      photography: 'A landscape photographer shifting to street photography: exposure intuition, composition rules, and post-processing workflows transfer; only subject approach changes.',
      travel:      'An experienced Europe traveller visiting Japan: language aside, the skills of navigating metros, finding food, and managing jet lag all transfer directly.',
      movies:      'A documentary director making their first fiction film: non-verbal storytelling, pacing instincts, and crew management all transfer; only scripted performance is new.',
      fitness:     'An elite swimmer moving to open-water racing: cardio engine, stroke efficiency, and pacing strategy all transfer — adaptation to waves and navigation is the delta.',
      chess:       'A chess grandmaster learning Go: pattern recognition discipline, calculation depth, and strategic thinking transfer — only the rules and piece interactions are new.',
      cooking:     'A French-trained chef cooking Thai food: knife skills, heat control, and sauce-making technique all transfer — only the flavour profiles and spice combinations need learning.',
      finance:     'An equity analyst moving to credit: financial statement analysis, ratio interpretation, and valuation thinking all transfer — just add covenant analysis.',
      business:    'A successful SaaS founder launching a marketplace: product sense, hiring instincts, and fundraising skills transfer — only the supply/demand-balance challenge is new.',
      sports:      'A decathlete specialising in the 400m hurdles: aerobic base, general athleticism, and race tactics all transfer; only the technical hurdling mechanics need work.',
    },
    {
      id: 'gpu-acceleration',
      name: 'GPU Acceleration',
      cricket:     'Sending the full squad to the nets simultaneously instead of one batter at a time. Parallel practice means the whole team improves at once.',
      gaming:      'Rendering thousands of particles, shadows, and AI agents simultaneously — a single GPU core would take hours; thousands of shader cores make it real-time.',
      music:       'A full orchestra performing live vs one musician re-recording each part separately. Parallelism is the difference between a symphony and a one-man-band.',
      photography: 'Batch-exporting 500 RAW files at once using all CPU cores versus processing them one by one in sequence — same output, a fraction of the time.',
      travel:      'Checking in an entire aircraft worth of passengers simultaneously at multiple desks versus one agent handling every boarding pass in a single queue.',
      movies:      'Rendering a VFX-heavy film on a render farm with thousands of nodes versus a single workstation. The farm finishes overnight; the workstation takes weeks.',
      fitness:     'A relay team where all four sprinters train their leg simultaneously (in parallel sessions) vs a coach teaching each runner back-to-back across four days.',
      chess:       'An engine evaluating millions of positions in parallel branches simultaneously versus a human calculating one variation at a time.',
      cooking:     'A restaurant kitchen with ten chefs each handling a different course versus one chef cooking every dish sequentially — parallel throughput is the core advantage.',
      finance:     'Running 10,000 Monte Carlo simulations in parallel across GPU cores versus sequentially — risk analysis that took hours now completes in seconds.',
      business:    'A BPO team handling 500 customer queries simultaneously versus one agent resolving them in a serial queue — parallelism defines throughput capacity.',
      sports:      'A sports analytics lab processing every player\'s wearable data streams simultaneously versus aggregating them one athlete at a time.',
    },
  ],
}

export default analogies
